import {icon} from './icons.js';
import {FACES,COLORS,NAMES,LABELS} from './cube-core.js';
import {lab,classifySample,calibrationError,sampleFace,stableFrames,validFace} from './scan-colours.js';
import {connectPhone,phoneToken,makeToken,drawQR} from './phone-link.js';
const instructions={U:'Look down at white. Blue is at the top of the image.',R:'Look at red. White is at the top of the image.',F:'Look at green. White is at the top of the image.',D:'Look at yellow. Green is at the top of the image.',L:'Look at orange. White is at the top of the image.',B:'Look at blue. White is at the top of the image.'};
export function initScanner({getFace,onFace,canEdit}){
 const $=id=>document.getElementById(id),dialog=$('scan-dialog'),isPhone=!!phoneToken();
 dialog.innerHTML=`<button class="close" aria-label="Close scanner">${icon('close')}</button><span class="eyebrow">LIVE CUBE SCANNER</span><h2 id="live-title">Colours that match your cube.</h2><p id="live-instruction"></p><div id="phone-banner" hidden></div><div class="scanner-source"><button id="start-camera" class="primary">${icon('camera')} Start camera</button><label class="outline">Choose photo<input id="scan-file" type="file" accept="image/*"></label></div><p id="scan-message" class="scan-message" role="status" aria-live="polite"></p><div class="live-frame"><video id="live-video" playsinline muted hidden></video><canvas id="live-canvas" width="480" height="480"></canvas><div id="live-overlay" class="live-overlay"></div><span id="live-empty">Camera images stay on this device.</span></div><div id="photo-adjustments" hidden><label class="speed">Photo zoom<input id="photo-scale" type="range" min="1" max="4" step=".02" value="1"></label><button class="outline" id="scan-rotate">${icon('rotate-cw')} Rotate photo</button><small>Drag the photo until all squares line up with the guide.</small></div><div id="calibration-dots" class="calibration-dots"></div><div id="scan-face-choice" class="scan-face-choice" hidden></div><div id="scan-review" hidden><h3>Review before using</h3><p>Compare every square with your cube. Tap a dotted square to accept its prediction; tap again to change its colour. Check every square.</p><div id="review-grid" class="review-grid"></div></div><div class="scanner-actions"><button id="capture-scan" class="primary" disabled>Save centre colour</button><button id="review-anyway" class="outline" hidden disabled>Review current colours manually</button><button id="retake-scan" class="outline" hidden>Scan again</button><button id="confirm-scan" class="primary" hidden>Use this face</button></div><button id="recalibrate" class="restart" hidden>Recalibrate colours</button><p class="fine-print">Use soft, even light. Keep the face straight and fill the guide. Face rotations are checked automatically when you solve. Calibration belongs to this cube and these lighting conditions; repeat it if either changes.</p>`;
 const canvas=$('live-canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),video=$('live-video');let stream=null,timer=null,frame=null,history=[],references={},calibration=0,target=getFace(),review=null,uncertain=[],photo=null,angle=0,offset=[0,0],request=0,stable=false,referenceHistory=[],pair=null,desktopPair=null,pending=null,pendingTimer=null,seen=new Set(),received=new Set(),phoneConnected=false;
 const message=(s,error=false)=>{$('scan-message').textContent=s;$('scan-message').classList.toggle('error',error);};
 function drawHeader(){const calibrating=calibration<6;$('live-title').textContent=calibrating?`Calibrate ${NAMES[FACES[calibration]].toLowerCase()}.`:`Scan the ${LABELS[target].toLowerCase()} face.`;$('live-instruction').textContent=calibrating?`Step ${calibration+1} of 6: put the ${NAMES[FACES[calibration]].toLowerCase()} centre inside the middle square. Save its colour, then show the next centre.`:instructions[target];$('capture-scan').textContent=calibrating?'Save centre colour':'Capture stable face';$('capture-scan').disabled=true;$('calibration-dots').innerHTML=FACES.map((f,i)=>`<span class="${i===calibration?'current':''} ${references[f]?'saved':''}" style="--chip:${references[f]?`rgb(${references[f].join(',')})`:COLORS[f]}"><i></i>${NAMES[f]}${references[f]?' ✓':''}</span>`).join('');$('scan-face-choice').hidden=calibrating;$('scan-face-choice').innerHTML=FACES.map(f=>`<button data-scan-face="${f}" aria-pressed="${target===f}" ${pending?'disabled':''}>${f}<small>${LABELS[f]}</small></button>`).join('');$('review-anyway').hidden=calibrating||!!review;$('recalibrate').hidden=calibrating||!!review;$('live-overlay').classList.toggle('calibrating',calibrating);if(!frame)$('live-overlay').innerHTML=Array.from({length:9},(_,i)=>`<span class="${i===4?'centre-sample':''}"></span>`).join('');}
 function stopCamera(){request++;if(timer)clearInterval(timer);timer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$('start-camera').textContent='Start camera';}
 async function startCamera(){if(stream){stopCamera();message('Camera stopped.');return;}stopCamera();photo?.close();photo=null;$('photo-adjustments').hidden=true;const current=++request;$('start-camera').disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Live camera needs HTTPS. Open the live website or choose photos.');const media=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280}}});if(current!==request||!dialog.open){media.getTracks().forEach(t=>t.stop());return;}stream=media;video.srcObject=media;await video.play();history=[];referenceHistory=[];$('live-empty').hidden=true;timer=setInterval(()=>{if(!review&&!document.hidden&&video.readyState>=2){const size=Math.min(video.videoWidth,video.videoHeight);ctx.drawImage(video,(video.videoWidth-size)/2,(video.videoHeight-size)/2,size,size,0,0,480,480);analyse();}},140);message('Camera ready. Keep the cube steady and avoid reflections.');$('start-camera').innerHTML=`${icon('camera')} Stop camera`;}catch(e){message(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in browser settings, or choose a photo.':e.name==='NotFoundError'?'No camera found. Use “Scan from phone” on desktop, or choose photos.':e.message,true);}finally{$('start-camera').disabled=false;}}
 function analyse(){frame=sampleFace(ctx);if(calibration<6){const sample=frame[4];referenceHistory.push(sample.rgb);if(referenceHistory.length>6)referenceHistory.shift();const steady=referenceHistory.length===6&&referenceHistory.every(rgb=>Math.hypot(...rgb.map((v,i)=>v-sample.rgb[i]))<12);const error=calibrationError(sample.rgb,references);stable=sample.good&&!error&&(photo||steady);$('capture-scan').disabled=!stable;$('live-overlay').innerHTML=Array.from({length:9},(_,i)=>`<span class="${i===4?'centre-sample':''}">${i===4?`<i style="background:rgb(${sample.rgb})"></i>`:''}</span>`).join('');if(error)message(error,true);else message(stable?`Ready: save the ${NAMES[FACES[calibration]].toLowerCase()} centre.`:'Hold the centre steady inside the middle square.');return;}
 const predictions=frame.map(s=>({...classifySample(s.rgb,references),rgb:s.rgb,confident:s.good&&classifySample(s.rgb,references).confident}));history.push(predictions);if(history.length>6)history.shift();stable=photo?predictions.every(p=>p.confident)&&predictions[4].face===target:stableFrames(history,target);$('capture-scan').disabled=!stable;$('review-anyway').disabled=false;$('live-overlay').innerHTML=predictions.map((p,i)=>`<span class="${p.confident?'confident':'uncertain'}"><i style="background:${COLORS[p.face]||'#666'}"></i><small>${p.confident?NAMES[p.face]:'Check'}</small></span>`).join('');message(predictions[4].face!==target?`The centre does not match ${NAMES[target].toLowerCase()}. Check the face or recalibrate.`:stable?'Colours are steady. Capture this face.':'Hold still. Uncertain squares are marked for review.');}
 function showReview(){if(!frame)return;const centre=classifySample(frame[4].rgb,references);if(centre.face!==target){message('The centre does not match this face. Select the correct face or recalibrate before continuing.',true);return;}review=frame.map(s=>classifySample(s.rgb,references).face||target);uncertain=frame.map((s,i)=>i!==4&&(!s.good||!classifySample(s.rgb,references).confident));review[4]=target;$('scan-review').hidden=false;$('capture-scan').hidden=true;$('review-anyway').hidden=true;$('recalibrate').hidden=true;$('retake-scan').hidden=false;$('confirm-scan').hidden=false;$('scan-face-choice').querySelectorAll('button').forEach(b=>b.disabled=true);renderReview();message('Review all nine colours. The centre is fixed to the selected face.');}
 function renderReview(){$('review-grid').innerHTML=review.map((f,i)=>`<button data-review="${i}" style="background:${COLORS[f]}" class="${uncertain[i]?'needs-review':''}" aria-label="Square ${i+1}: ${NAMES[f]}${uncertain[i]?', needs review':''}" ${i===4||pending?'disabled':''}><span>${NAMES[f]}</span>${uncertain[i]?'<small>Check</small>':''}</button>`).join('');$('confirm-scan').disabled=!!pending||uncertain.some(Boolean);$('confirm-scan').textContent=pending?'Sending…':isPhone?'Send face to desktop':'Use this face';}
 function resetReview(){review=null;history=[];referenceHistory=[];$('scan-review').hidden=true;$('capture-scan').hidden=false;$('retake-scan').hidden=true;$('confirm-scan').hidden=true;drawHeader();if(photo)drawPhoto();}
 function open(){if(!canEdit()&&!isPhone)return;target=getFace();resetReview();if(!dialog.open)dialog.showModal();message(calibration<6?'First, teach the scanner your cube’s six centre colours.':'Your calibration is ready. Start the camera or choose a photo.');}
 $('photo-mode').onclick=open;$('manual-mode').onclick=()=>document.querySelector('#face-grid button:not(:disabled)')?.focus();$('start-camera').onclick=startCamera;
 $('capture-scan').onclick=()=>{if(!stable||!frame)return;if(calibration<6){references[FACES[calibration]]=frame[4].rgb;calibration++;referenceHistory=[];history=[];stable=false;drawHeader();message(calibration<6?'Centre saved. Show the next colour.':'Calibration complete. Align all nine squares with the guide.');if(photo){photo.close();photo=null;frame=null;$('photo-adjustments').hidden=true;ctx.clearRect(0,0,480,480);$('live-empty').hidden=false;}}else showReview();};$('review-anyway').onclick=showReview;$('retake-scan').onclick=()=>{if(!pending)resetReview();};$('recalibrate').onclick=()=>{references={};calibration=0;resetReview();message('Start again with the white centre.');};
 $('review-grid').onclick=e=>{const b=e.target.closest('[data-review]');if(!b||pending)return;const i=Number(b.dataset.review);if(i===4)return;if(uncertain[i])uncertain[i]=false;else review[i]=FACES[(FACES.indexOf(review[i])+1)%6];renderReview();};
 $('scan-face-choice').onclick=e=>{const b=e.target.closest('[data-scan-face]');if(!b||pending)return;target=b.dataset.scanFace;resetReview();};
 function finishLocal(face,colours){if(!validFace(face,colours))return;onFace(face,colours);received.add(face);target=FACES.find(f=>!received.has(f))||face;resetReview();message(received.size===6?'All six faces captured. Close the scanner and find your solution.':`${NAMES[face]} face saved. Continue with ${NAMES[target].toLowerCase()}.`);}
 $('confirm-scan').onclick=async()=>{if(!review||uncertain.some(Boolean)||pending)return;const colours=review.join('');if(!isPhone){finishLocal(target,colours);return;}if(!pair||!phoneConnected){message('Desktop is not connected. Keep the QR window open and wait for reconnection.',true);return;}pending={face:target,colours,messageId:crypto.randomUUID(),attempts:0};renderReview();sendPending();pendingTimer=setInterval(sendPending,2000);};
 async function sendPending(){if(!pending)return;if(++pending.attempts>12){clearInterval(pendingTimer);pending=null;renderReview();message('Desktop did not confirm receipt. Your review is still here; reconnect and try again.',true);return;}try{await pair.send('face',pending);}catch(e){message(e.message,true);}}
 function drawPhoto(){if(!photo)return;const w=angle%2?photo.height:photo.width,h=angle%2?photo.width:photo.height,s=Math.min(480/w,480/h)*Number($('photo-scale').value);ctx.fillStyle='#111811';ctx.fillRect(0,0,480,480);ctx.save();ctx.translate(240+offset[0],240+offset[1]);ctx.rotate(angle*Math.PI/2);ctx.drawImage(photo,-photo.width*s/2,-photo.height*s/2,photo.width*s,photo.height*s);ctx.restore();analyse();}
 $('scan-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>25*1024*1024){message('Choose an image under 25 MB.',true);return;}stopCamera();try{photo?.close();photo=await createImageBitmap(file);angle=0;offset=[0,0];$('photo-scale').value='1';$('photo-adjustments').hidden=false;$('live-empty').hidden=true;resetReview();drawPhoto();}catch{message('Could not read that image. Try JPG, PNG or WebP.',true);}e.target.value='';};$('photo-scale').oninput=drawPhoto;$('scan-rotate').onclick=()=>{angle++;offset=[0,0];drawPhoto();};let drag=null;canvas.onpointerdown=e=>{if(!photo||review)return;drag=[e.clientX,e.clientY,...offset];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const s=480/canvas.clientWidth;offset=[drag[2]+(e.clientX-drag[0])*s,drag[3]+(e.clientY-drag[1])*s];drawPhoto();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
 dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{stopCamera();if(isPhone){pair?.close();pair=null;clearInterval(pendingTimer);pending=null;phoneConnected=false;}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera();if(dialog.open)message('Camera paused. Tap Start camera when you return.');}});window.addEventListener('pagehide',()=>{stopCamera();pair?.close();desktopPair?.close();clearInterval(pendingTimer);});
 // Desktop pairing: the high-entropy link contains no photos or cube state.
 const phoneDialog=document.createElement('dialog');phoneDialog.id='phone-pair-dialog';phoneDialog.innerHTML=`<button class="close" aria-label="Close phone pairing">${icon('close')}</button><span class="eyebrow">SCAN FROM YOUR PHONE</span><h2>Your phone is the camera.</h2><p>Keep this window open. Scan the QR code, calibrate the six centres, then review and send each face.</p><canvas id="phone-qr" aria-label="QR code to connect your phone"></canvas><p id="pair-status" role="status" aria-live="polite">Connecting…</p><div id="paired-faces" class="calibration-dots"></div><button id="copy-phone-link" class="outline" disabled>Copy phone link</button><p class="fine-print">The link expires after 20 minutes. Only reviewed sticker colours are relayed through our connection service; no photos or video leave your phone. Keep this link private.</p>`;document.body.append(phoneDialog);
 const phoneButton=document.createElement('button');phoneButton.id='scan-from-phone';phoneButton.className='phone-launch';phoneButton.innerHTML=`${icon('camera')} Scan from phone <span>QR</span>`;$('photo-mode').closest('.input-modes').after(phoneButton);
 phoneDialog.querySelector('.close').onclick=()=>phoneDialog.close();phoneDialog.addEventListener('close',()=>{desktopPair?.close();desktopPair=null;});
 phoneButton.onclick=async()=>{if(!canEdit())return;phoneDialog.showModal();$('pair-status').textContent='Creating your connection…';$('phone-qr').hidden=true;$('copy-phone-link').disabled=true;received.clear();seen.clear();try{desktopPair?.close();const token=makeToken();const url=new URL('/tools/rubiks-cube/',location.origin);if(['localhost','127.0.0.1'].includes(url.hostname)){url.hostname='hisanali.com';url.port='';url.protocol='https:';}url.hash=`phone=${token}`;desktopPair=await connectPhone({token,role:'desktop',onStatus:s=>{$('pair-status').textContent=s;},onMessage:(p,send)=>{if(p.type==='hello'){send('welcome',{face:FACES.find(f=>!received.has(f))||getFace()}).catch(()=>{});$('pair-status').textContent=received.size===6?'All six faces received. Close this window to check and solve your cube.':`Phone connected. ${received.size} of 6 faces received.`;}if(p.type==='face'){if(!canEdit()){ $('pair-status').textContent='Pause the solver and return to Set up to receive colours.';return;}if(!seen.has(p.messageId)){onFace(p.face,p.colours);received.add(p.face);seen.add(p.messageId);$('paired-faces').innerHTML=FACES.map(f=>`<span class="${received.has(f)?'saved':''}">${NAMES[f]} ${received.has(f)?'✓':'—'}</span>`).join('');}send('ack',{messageId:p.messageId,face:FACES.find(f=>!received.has(f))||p.face}).catch(()=>{});$('pair-status').textContent=received.size===6?'All six faces received. Close this window to check and solve your cube.':`${received.size} of 6 faces received. ${NAMES[p.face]} updated.`;}}});if(!phoneDialog.open){desktopPair.close();desktopPair=null;return;}await drawQR($('phone-qr'),url.href);$('phone-qr').hidden=false;$('copy-phone-link').disabled=false;$('pair-status').textContent='Waiting for your phone. The QR code is ready.';$('copy-phone-link').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);$('pair-status').textContent='Link copied. Open it on your phone.';}catch{$('pair-status').textContent=url.href;}};}catch(e){$('pair-status').textContent=e.message;}};
 if(isPhone){phoneButton.hidden=true;document.body.classList.add('phone-scanner-page');const launch=document.createElement('button');launch.className='primary phone-resume';launch.textContent='Open phone scanner';document.querySelector('.intro').prepend(launch);const join=async()=>{open();$('phone-banner').hidden=false;$('phone-banner').textContent='Connecting to your desktop…';try{pair?.close();pair=await connectPhone({token:phoneToken(),role:'phone',onStatus:s=>{$('phone-banner').textContent=s;},onMessage:(p)=>{if(p.type==='welcome'){phoneConnected=true;$('phone-banner').textContent='Connected to desktop. Reviewed faces will sync there.';if(!review&&calibration<6){target=p.face;drawHeader();}}if(p.type==='ack'&&pending&&p.messageId===pending.messageId){clearInterval(pendingTimer);received.add(pending.face);pending=null;if(FACES.includes(p.face))target=p.face;resetReview();message(received.size===6?'All six faces sent. Return to your desktop to solve.':'Face received by desktop. Continue with the next face.');}}});if(!dialog.open){pair.close();pair=null;return;}await pair.send('hello');}catch(e){message(e.message,true);}};launch.onclick=join;join();}
}
