import {initScanner} from './live-scanner.js';
import {icon} from './icons.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import Cube from './vendor/cube.js';
import {FACES,COLORS,NAMES,LABELS,SOLVED,NORMALS,position,inverse,validate,correctOrientation} from './cube-core.js';
const $=id=>document.getElementById(id);
const hints=Object.fromEntries(FACES.map(f=>[f,`Match the ${NAMES[f].toLowerCase()}-centred face. We check face rotations automatically when solving.`]));
let state=SOLVED,original=SOLVED,face=2,colour='F',moves=[],step=0,playing=false,busy=false,solving=false,mode='setup',entryView='choice',worker,timeout,scanError=null;
try{const saved=JSON.parse(localStorage.getItem('hisan-cube-studio-v1'));if(saved&&/^[URFDLB]{54}$/.test(saved.state)&&FACES.every((f,i)=>saved.state[i*9+4]===f)){state=saved.state;scanError=typeof saved.scanError==='string'?saved.scanError:null;if(Number.isInteger(saved.face)&&saved.face>=0&&saved.face<6)face=saved.face;if(saved.original&&!validate(saved.original,Cube)&&Array.isArray(saved.moves)&&saved.moves.length<=40&&saved.moves.every(m=>/^[URFDLB](2|')?$/.test(m))&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<=saved.moves.length&&Cube.fromString(saved.original).move(saved.moves.join(' ')).isSolved()&&Cube.fromString(saved.original).move(saved.moves.slice(0,saved.step).join(' ')).asString()===state){original=saved.original;moves=saved.moves;step=saved.step;mode=saved.mode==='solution'?'solution':'setup';}}}catch{}
function save(){try{localStorage.setItem('hisan-cube-studio-v1',JSON.stringify({state,face,original,moves,step,mode,scanError}));}catch{}}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
let scene,camera,renderer,controls,root,cubies=[],stickers=[],activeTurn=null,guide;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function init3d(){try{
 const host=$('viewport');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(6.8,5.5,8.1);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.append(renderer.domElement);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=25;controls.target.set(0,0,0);controls.update();
 scene.add(new THREE.AmbientLight(0xffffff,1.15));const key=new THREE.DirectionalLight(0xffffff,1.8);key.position.set(3,8,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.normalBias=.03;scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,.8);fill.position.set(-5,2,-3);scene.add(fill);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.22}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.05;floor.receiveShadow=true;scene.add(floor);
 root=new THREE.Group();scene.add(root);buildCube();new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);fitCamera();}).observe(host);
 let startPoint;host.addEventListener('pointerdown',e=>startPoint=[e.clientX,e.clientY]);host.addEventListener('pointerup',e=>{if(!startPoint||Math.hypot(e.clientX-startPoint[0],e.clientY-startPoint[1])>5||mode!=='setup'||busy||solving)return;const rect=host.getBoundingClientRect();const pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(stickers)[0];if(hit)paint(hit.object.userData.index);});
 renderer.setAnimationLoop(t=>{if(document.hidden)return;if(activeTurn){const a=activeTurn;const p=Math.min((t-a.start)/a.duration,1);a.group.quaternion.setFromAxisAngle(a.axis,a.angle*(p*p*(3-2*p)));if(p===1){activeTurn=null;a.finish();}}controls.update();renderer.render(scene,camera);});
 }catch(e){$('webgl-error').hidden=false;console.warn('3D unavailable',e);}}
const bodyGeometry=new RoundedBoxGeometry(.955,.955,.955,3,.065);
const tileGeometry=new RoundedBoxGeometry(.827,.827,.035,3,.06);
const bodyMaterial=new THREE.MeshStandardMaterial({color:0x111613,roughness:.29,metalness:.12});
const tileMaterials=Object.fromEntries(FACES.map(f=>[f,new THREE.MeshPhysicalMaterial({color:COLORS[f],roughness:.48,metalness:0,clearcoat:.15,clearcoatRoughness:.4,toneMapped:false})]));
function buildCube(){if(!root)return;root.clear();cubies=[];stickers=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){if(!x&&!y&&!z)continue;const group=new THREE.Group();group.position.set(x,y,z);group.userData.pos=[x,y,z];const body=new THREE.Mesh(bodyGeometry,bodyMaterial);body.castShadow=true;body.receiveShadow=true;group.add(body);root.add(group);cubies.push(group);}
 FACES.forEach((f,fi)=>{for(let r=0;r<3;r++)for(let c=0;c<3;c++){const pos=position(f,r,c);const cubie=cubies.find(g=>g.userData.pos.every((v,i)=>v===pos[i]));const index=fi*9+r*3+c;const normal=new THREE.Vector3(...NORMALS[f]);const tile=new THREE.Mesh(tileGeometry,tileMaterials[state[index]]);tile.position.copy(normal.clone().multiplyScalar(.486));tile.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);tile.userData.index=index;tile.castShadow=true;cubie.add(tile);stickers.push(tile);}});}
function paint(index){if(solving||busy||mode!=='setup')return;if(index%9===4){status('Centre squares identify each face and stay fixed.');return;}state=state.slice(0,index)+colour+state.slice(index+1);if(scanError){const aligned=correctOrientation(state,Cube,{requireUnique:true});scanError=aligned.error||null;if(!scanError)state=aligned.state;}moves=[];step=0;status('');buildCube();renderSetup();save();}
function renderSetup(){const f=FACES[face];$('face-title').textContent=`${LABELS[f]} face · ${NAMES[f]}`;$('face-number').textContent=`${String(face+1).padStart(2,'0')} / 06`;$('orientation').textContent=hints[f];$('palette').innerHTML=FACES.map(c=>{const n=state.split(c).length-1;return `<button class="swatch ${n>9?'over':''}" aria-label="Paint ${NAMES[c]}, ${n} of 9 squares" aria-pressed="${colour===c}" data-colour="${c}" ${solving?'disabled':''}><i style="background:${COLORS[c]}"></i><span>${n}/9</span></button>`;}).join('');$('face-grid').innerHTML=Array.from({length:9},(_,i)=>`<button class="sticker" style="background:${COLORS[state[face*9+i]]}" data-index="${face*9+i}" aria-label="${LABELS[f]} row ${Math.floor(i/3)+1} column ${i%3+1}: ${NAMES[state[face*9+i]]}${i===4?', fixed centre':''}" ${i===4||solving?'disabled':''}>${i===4?icon('focus'):''}</button>`).join('');$('face-tabs').innerHTML=FACES.map((f,i)=>`<button class="${i===face?'active':''}" data-face="${i}" aria-label="Edit ${LABELS[f]} face" aria-pressed="${i===face}">${f}</button>`).join('');}
function setFace(i){face=(i+6)%6;renderSetup();save();}
$('palette').onclick=e=>{const button=e.target.closest('[data-colour]');if(button){colour=button.dataset.colour;renderSetup();}};$('face-grid').onclick=e=>{const button=e.target.closest('[data-index]');if(button)paint(Number(button.dataset.index));};$('face-tabs').onclick=e=>{const button=e.target.closest('[data-face]');if(button)setFace(Number(button.dataset.face));};$('prev-face').onclick=()=>setFace(face-1);$('next-face').onclick=()=>setFace(face+1);
function showEntry(view='manual'){
 entryView=view;const chooser=$('method-chooser'),workbench=$('setup-workbench');if(chooser)chooser.hidden=view!=='choice';if(workbench)workbench.hidden=view==='choice';document.body.classList.toggle('entry-choice',view==='choice'&&mode==='setup');document.body.classList.toggle('entry-manual',view==='manual'&&mode==='setup');
}
function initEntryUI(){
 const panel=$('setup-panel'),existing=[...panel.children],workbench=document.createElement('div'),chooser=document.createElement('div');workbench.id='setup-workbench';existing.forEach(node=>workbench.append(node));chooser.id='method-chooser';chooser.innerHTML=`<span class="eyebrow">START HERE</span><h2>How should we read your cube?</h2><p>Choose the easiest way for you. You can change this later.</p><div class="method-list"><button id="choose-scan" class="method-choice recommended"><span class="method-icon">${icon('camera')}</span><span><strong>Scan my cube</strong><small>Show each face to the camera. Colours are captured automatically.</small></span><b>FASTEST</b>${icon('arrow-right')}</button><button id="choose-manual" class="method-choice"><span class="method-icon">${icon('grid')}</span><span><strong>Enter colours by hand</strong><small>Tap the nine squares on each face. About two minutes.</small></span>${icon('arrow-right')}</button></div><button id="choose-demo" class="demo-link">${icon('spark')} I just want to see how it works</button><p class="method-privacy">${icon('shield')} Private by design. Camera images never leave your device.</p>`;
 workbench.insertAdjacentHTML('afterbegin',`<button id="change-method" class="change-method">${icon('arrow-left')} Change input method</button>`);panel.append(chooser,workbench);
 const solutionEdit=document.createElement('button');solutionEdit.id='mobile-edit-cube';solutionEdit.className='solution-edit';solutionEdit.innerHTML=`${icon('arrow-left')} Edit cube`;$('solution-panel').prepend(solutionEdit);solutionEdit.onclick=()=>$('edit-tab').click();
 const compact=matchMedia('(max-width:850px)'),scanChoice=$('choose-scan');scanChoice.querySelector('strong').textContent=compact.matches?'Scan with this phone':'Scan with your phone';scanChoice.querySelector('small').textContent=compact.matches?'Point the camera at each face. Colours are captured automatically.':'Open a QR code, then point your phone at each face. No app needed.';scanChoice.onclick=()=>{showEntry('manual');requestAnimationFrame(()=>$(compact.matches?'photo-mode':'scan-from-phone')?.click());};$('choose-manual').onclick=()=>{showEntry('manual');if(!compact.matches)requestAnimationFrame(()=>document.querySelector('#face-grid button:not(:disabled)')?.focus());};$('change-method').onclick=()=>showEntry('choice');$('choose-demo').onclick=()=>{showEntry('manual');$('scramble').click();setTimeout(()=>$('solve').click(),120);};
 document.querySelector('.intro .eyebrow').innerHTML=`${icon('cube')} PRIVATE 3D CUBE GUIDE`;document.querySelector('.intro h1').innerHTML='Solve your cube.<br><em>One clear turn at a time.</em>';document.querySelector('.intro p').innerHTML='Scan or enter six faces. Then follow every move on a cube you can rotate, pause and replay.';document.querySelector('.intro-aside').innerHTML=`<span class="mini-mark">${icon('spark')}</span><span><strong>Three calm steps.</strong><br>Capture · Check · Solve</span>`;
 $('edit-tab').innerHTML='<b>1</b><span>Capture</span>';$('solve-tab').innerHTML='<b>2</b><span>Follow</span>';document.querySelector('.stage-title').innerHTML='YOUR CUBE <span>LIVE 3D</span>';document.querySelector('.stage-watermark').textContent='HOLD · TURN · FOLLOW';
 const heading=workbench.querySelector('.panel-heading');heading.querySelector('h2').textContent='Match one face at a time.';heading.querySelector('p').textContent='Pick a colour, then tap its square.';
 const guide=document.querySelector('.cube-field-guide'),knowledgeHeading=guide?.querySelector('.knowledge-heading');if(guide&&knowledgeHeading){const toggle=document.createElement('button');toggle.id='learn-toggle';toggle.className='knowledge-trigger';toggle.innerHTML=`<span>${icon('spark')} Learn the cube in 3 minutes</span><small>Centres, pieces, layers and notation</small>${icon('arrow-right')}`;knowledgeHeading.append(toggle);toggle.onclick=()=>{const open=guide.classList.toggle('is-open');toggle.setAttribute('aria-expanded',String(open));toggle.querySelector('.icon-arrow-right').style.transform=`rotate(${open?90:0}deg)`;};toggle.setAttribute('aria-expanded','false');}
 showEntry(mode==='solution'?'manual':'choice');
}
function setMode(next){mode=next;document.body.classList.toggle('is-solving',mode==='solution');updateGuide();$('setup-panel').hidden=mode!=='setup';$('solution-panel').hidden=mode!=='solution';$('edit-tab').classList.toggle('active',mode==='setup');$('solve-tab').classList.toggle('active',mode==='solution');showEntry(entryView);save();}
$('edit-tab').onclick=()=>{if(busy||solving)return;playing=false;setMode('setup');showEntry('manual');renderSetup();status('Edit the current cube, then find a new solution.');};$('solve-tab').onclick=()=>{if(solving||busy)return;if(moves.length){setMode('solution');renderSolution();}else if(entryView==='choice'){showEntry('manual');status('Add your cube first, then find its solution.');}else $('solve').click();};
function fitCamera(){if(!camera)return;const distance=11.9/Math.min(1,Math.max(.35,camera.aspect));camera.position.setLength(distance);controls.update();}
function resetView(){if(!camera)return;camera.position.set(6.8,5.5,8.1);controls.target.set(0,0,0);fitCamera();} $('reset-view').onclick=resetView;
$('scramble').onclick=()=>{if(busy||solving)return;showEntry('manual');scanError=null;state=Cube.random().asString();moves=[];step=0;playing=false;buildCube();renderSetup();save();status('A fresh scramble. Solve it to try the full experience.');};
$('clear').onclick=()=>{if(busy||solving)return;scanError=null;state=SOLVED;moves=[];step=0;buildCube();renderSetup();save();status('Reset to a solved cube. Paint the squares to match yours.');};
function revealSolution(){if(matchMedia('(max-width:850px)').matches)requestAnimationFrame(()=>$('solution-panel').scrollIntoView({block:'start',behavior:reduced?'instant':'smooth'}));}
function unlock(){solving=false;$('solve').disabled=false;$('solve').innerHTML=`Find my solution ${icon('arrow-up-right')}`;renderSetup();}
$('solve').onclick=()=>{if(solving||busy)return;if(scanError){status(scanError,true);return;}original=state;playing=false;if(state===SOLVED){moves=[];step=0;setMode('solution');renderSolution();revealSolution();status('This cube is already solved. Try a scramble or edit your colours.');return;}solving=true;$('solve').disabled=true;$('solve').textContent='Finding your way…';renderSetup();status('Finding a solution on your device…');
 try{if(!worker){worker=new Worker('/tools/rubiks-cube/solver.bundle.js');worker.onmessage=({data})=>{if(data.status){status(data.status);return;}clearTimeout(timeout);unlock();if(data.error){status(data.error,true);return;}state=data.state;original=state;buildCube();renderSetup();moves=data.algorithm.trim().split(/\s+/).filter(Boolean);step=0;setMode('solution');resetView();renderSolution();revealSolution();status(`${data.corrected?'Face rotations corrected automatically. ':''}${moves.length} moves to clarity. Follow the next turn below.`);};worker.onerror=()=>{clearTimeout(timeout);worker.terminate();worker=null;unlock();status('The solver could not load. Please reload and try again.',true);};}worker.postMessage({state});timeout=setTimeout(()=>{worker.terminate();worker=null;unlock();status('This solve took too long. Your colours are saved; please try again.',true);},60000);}catch{unlock();status('This browser could not start the solver. Please try a current browser.',true);}};
function updateGuide(){if(!scene)return;if(guide){scene.remove(guide);guide.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});guide=null;}if(mode!=='solution'||step>=moves.length||busy)return;
 guide=new THREE.Group();const move=moves[step],normal=new THREE.Vector3(...NORMALS[move[0]]);guide.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);guide.position.copy(normal.multiplyScalar(1.56));
 const points=[[-1.53,-1.53,0],[1.53,-1.53,0],[1.53,1.53,0],[-1.53,1.53,0]].map(p=>new THREE.Vector3(...p));guide.add(new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xd6ed99,transparent:true,opacity:.75})));
 const clockwise=!move.endsWith("'");const curve=[];for(let i=0;i<=35;i++){const a=(clockwise?-1:1)*i/35*Math.PI*.68+Math.PI*.65;curve.push(new THREE.Vector3(Math.cos(a)*1.84,Math.sin(a)*1.84,.03));}guide.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve),new THREE.LineBasicMaterial({color:0xd6ed99})));const tip=new THREE.Mesh(new THREE.ConeGeometry(.075,.22,12),new THREE.MeshBasicMaterial({color:0xd6ed99}));tip.position.copy(curve.at(-1));tip.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),curve.at(-1).clone().sub(curve.at(-2)).normalize());guide.add(tip);scene.add(guide);
}
function renderSolution(){updateGuide();const done=step>=moves.length;const move=moves[step];$('move-count').textContent=done?'ALL SIDES, IN HARMONY':`NEXT · MOVE ${String(step+1).padStart(2,'0')} OF ${moves.length}`;$('move-symbol').innerHTML=done?icon('check'):move.replace("'",'′');$('move-description').textContent=done?'You’ve brought it all together.':`Turn the ${NAMES[move[0]].toLowerCase()}-centre (${LABELS[move[0]].toLowerCase()}) face ${move.endsWith('2')?'180°':move.endsWith("'")?'counterclockwise':'clockwise'}.`;$('solution-title').textContent=done?'Hello, clarity.':'Your way to solved.';$('move-perspective').textContent=done?'Every face is complete. Nicely done.':'Clockwise is viewed looking directly at that face.';$('progress').style.width=`${moves.length?step/moves.length*100:100}%`;$('play').innerHTML=playing?`${icon('pause')}<span>Pause</span>`:`${icon('play')}<span>Play solution</span>`;$('play').disabled=done;$('previous').disabled=step===0||busy;$('next').disabled=done||busy;$('restart').disabled=busy||step===0;$('move-list').innerHTML=moves.map((m,i)=>`<span class="${i<step?'done':i===step?'current':''}" ${i===step?'aria-current="step"':''}>${i+1}. ${m.replace("'",'′')}</span>`).join('');}
let animationDuration=750;
function animateMove(move){if(guide)guide.visible=false;return new Promise(resolve=>{if(!renderer||!root){state=Cube.fromString(state).move(move).asString();resolve();return;}const group=new THREE.Group();root.add(group);const axis=new THREE.Vector3(...NORMALS[move[0]]);cubies.filter(c=>new THREE.Vector3(...c.userData.pos).dot(axis)>.5).forEach(c=>group.attach(c));activeTurn={group,axis,angle:-Math.PI/2*(move.endsWith('2')?2:move.endsWith("'")?-1:1),start:performance.now(),duration:reduced?1:animationDuration,finish:()=>{state=Cube.fromString(state).move(move).asString();buildCube();resolve();}};});}
async function advance(direction){if(busy||solving||direction===1&&step>=moves.length||direction===-1&&step<=0)return;busy=true;renderSolution();await animateMove(direction===1?moves[step]:inverse(moves[step-1]));step+=direction;busy=false;if(step===moves.length)playing=false;renderSolution();save();if(playing)setTimeout(()=>{if(playing)advance(1);},reduced?600:350);}
$('speed').onclick=e=>{const button=e.target.closest('[data-speed]');if(!button)return;animationDuration=Number(button.dataset.speed);$('speed').querySelectorAll('[data-speed]').forEach(option=>option.setAttribute('aria-pressed',String(option===button)));};
$('next').onclick=()=>{playing=false;advance(1);};$('previous').onclick=()=>{playing=false;advance(-1);};$('play').onclick=()=>{playing=!playing;renderSolution();if(playing&&!busy)advance(1);};$('restart').onclick=()=>{if(busy)return;playing=false;state=original;step=0;buildCube();renderSolution();save();status('Back at the beginning. Keep white on top and green in front.');};
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;renderSolution();}});
$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
function applyScannedCube(faces){const scanned=FACES.map(f=>faces[f]).join(''),aligned=correctOrientation(scanned,Cube,{requireUnique:true});scanError=aligned.error||null;state=aligned.error?scanned:aligned.state;moves=[];step=0;face=2;showEntry('manual');buildCube();renderSetup();resetView();save();status(aligned.error?`The scan is complete, but one face could not be aligned safely. ${aligned.error}`:'Scan aligned automatically. The 3D view now uses white on top and green in front.',!!aligned.error);return aligned;}
initScanner({getFace:()=>FACES[face],canEdit:()=>mode==='setup'&&!busy&&!solving,onFace:(f,colours)=>{const i=FACES.indexOf(f);state=state.slice(0,i*9)+colours+state.slice(i*9+9);moves=[];step=0;face=i;showEntry('manual');buildCube();renderSetup();save();status(`${NAMES[f]} face received. Aligning after all six arrive…`);},onComplete:applyScannedCube});
init3d();renderSetup();setMode(mode);renderSolution();initEntryUI();if(scanError)status(scanError,true);else if(state!==SOLVED)status('Your saved cube is ready whenever you are.');
