import {icon} from './icons.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import Cube from './vendor/cube.js';
import {FACES,COLORS,NAMES,LABELS,SOLVED,NORMALS,position,inverse,validate} from './cube-core.js';
const $=id=>document.getElementById(id);
const hints={U:'Look down at white. Keep the blue centre at the top.',R:'Look at red. Keep the white centre at the top.',F:'Look at green. Keep the white centre at the top.',D:'Look at yellow. Keep the green centre at the top.',L:'Look at orange. Keep the white centre at the top.',B:'Look at blue. Keep the white centre at the top.'};
let state=SOLVED,original=SOLVED,face=2,colour='F',moves=[],step=0,playing=false,busy=false,solving=false,mode='setup',worker,timeout;
try{const saved=JSON.parse(localStorage.getItem('hisan-cube-studio-v1'));if(saved&&/^[URFDLB]{54}$/.test(saved.state)&&FACES.every((f,i)=>saved.state[i*9+4]===f)){state=saved.state;if(Number.isInteger(saved.face)&&saved.face>=0&&saved.face<6)face=saved.face;if(saved.original&&!validate(saved.original,Cube)&&Array.isArray(saved.moves)&&saved.moves.length<=40&&saved.moves.every(m=>/^[URFDLB](2|')?$/.test(m))&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<=saved.moves.length&&Cube.fromString(saved.original).move(saved.moves.join(' ')).isSolved()&&Cube.fromString(saved.original).move(saved.moves.slice(0,saved.step).join(' ')).asString()===state){original=saved.original;moves=saved.moves;step=saved.step;mode=saved.mode==='solution'?'solution':'setup';}}}catch{}
function save(){try{localStorage.setItem('hisan-cube-studio-v1',JSON.stringify({state,face,original,moves,step,mode}));}catch{}}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
let scene,camera,renderer,controls,root,cubies=[],stickers=[],activeTurn=null,guide;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function init3d(){try{
 const host=$('viewport');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(6.8,5.5,8.1);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.append(renderer.domElement);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=25;controls.target.set(0,0,0);controls.update();
 scene.add(new THREE.AmbientLight(0xc5d5bc,1.6));const key=new THREE.DirectionalLight(0xfff7e3,3);key.position.set(3,8,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.normalBias=.03;scene.add(key);const fill=new THREE.DirectionalLight(0xb6caff,1.4);fill.position.set(-5,2,-3);scene.add(fill);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.22}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.05;floor.receiveShadow=true;scene.add(floor);
 root=new THREE.Group();scene.add(root);buildCube();new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);fitCamera();}).observe(host);
 let startPoint;host.addEventListener('pointerdown',e=>startPoint=[e.clientX,e.clientY]);host.addEventListener('pointerup',e=>{if(!startPoint||Math.hypot(e.clientX-startPoint[0],e.clientY-startPoint[1])>5||mode!=='setup'||busy||solving)return;const rect=host.getBoundingClientRect();const pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(stickers)[0];if(hit)paint(hit.object.userData.index);});
 renderer.setAnimationLoop(t=>{if(document.hidden)return;if(activeTurn){const a=activeTurn;const p=Math.min((t-a.start)/a.duration,1);a.group.quaternion.setFromAxisAngle(a.axis,a.angle*(p*p*(3-2*p)));if(p===1){activeTurn=null;a.finish();}}controls.update();renderer.render(scene,camera);});
 }catch(e){$('webgl-error').hidden=false;console.warn('3D unavailable',e);}}
const bodyGeometry=new RoundedBoxGeometry(.955,.955,.955,3,.065);
const tileGeometry=new RoundedBoxGeometry(.827,.827,.035,3,.06);
const bodyMaterial=new THREE.MeshStandardMaterial({color:0x111613,roughness:.29,metalness:.12});
const tileMaterials=Object.fromEntries(FACES.map(f=>[f,new THREE.MeshPhysicalMaterial({color:COLORS[f],roughness:.3,metalness:0,clearcoat:.45,clearcoatRoughness:.25})]));
function buildCube(){if(!root)return;root.clear();cubies=[];stickers=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){if(!x&&!y&&!z)continue;const group=new THREE.Group();group.position.set(x,y,z);group.userData.pos=[x,y,z];const body=new THREE.Mesh(bodyGeometry,bodyMaterial);body.castShadow=true;body.receiveShadow=true;group.add(body);root.add(group);cubies.push(group);}
 FACES.forEach((f,fi)=>{for(let r=0;r<3;r++)for(let c=0;c<3;c++){const pos=position(f,r,c);const cubie=cubies.find(g=>g.userData.pos.every((v,i)=>v===pos[i]));const index=fi*9+r*3+c;const normal=new THREE.Vector3(...NORMALS[f]);const tile=new THREE.Mesh(tileGeometry,tileMaterials[state[index]]);tile.position.copy(normal.clone().multiplyScalar(.486));tile.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);tile.userData.index=index;tile.castShadow=true;cubie.add(tile);stickers.push(tile);}});}
function paint(index){if(solving||busy||mode!=='setup')return;if(index%9===4){status('Centre squares identify each face and stay fixed.');return;}state=state.slice(0,index)+colour+state.slice(index+1);moves=[];step=0;status('');buildCube();renderSetup();save();}
function renderSetup(){const f=FACES[face];$('face-title').textContent=`${LABELS[f]} face · ${NAMES[f]}`;$('face-number').textContent=`${String(face+1).padStart(2,'0')} / 06`;$('orientation').textContent=hints[f];$('palette').innerHTML=FACES.map(c=>{const n=state.split(c).length-1;return `<button class="swatch ${n>9?'over':''}" aria-label="Paint ${NAMES[c]}, ${n} of 9 squares" aria-pressed="${colour===c}" data-colour="${c}" ${solving?'disabled':''}><i style="background:${COLORS[c]}"></i><span>${n}/9</span></button>`;}).join('');$('face-grid').innerHTML=Array.from({length:9},(_,i)=>`<button class="sticker" style="background:${COLORS[state[face*9+i]]}" data-index="${face*9+i}" aria-label="${LABELS[f]} row ${Math.floor(i/3)+1} column ${i%3+1}: ${NAMES[state[face*9+i]]}${i===4?', fixed centre':''}" ${i===4||solving?'disabled':''}>${i===4?icon('focus'):''}</button>`).join('');$('face-tabs').innerHTML=FACES.map((f,i)=>`<button class="${i===face?'active':''}" data-face="${i}" aria-label="Edit ${LABELS[f]} face" aria-pressed="${i===face}">${f}</button>`).join('');}
function setFace(i){face=(i+6)%6;renderSetup();save();}
$('palette').onclick=e=>{const button=e.target.closest('[data-colour]');if(button){colour=button.dataset.colour;renderSetup();}};$('face-grid').onclick=e=>{const button=e.target.closest('[data-index]');if(button)paint(Number(button.dataset.index));};$('face-tabs').onclick=e=>{const button=e.target.closest('[data-face]');if(button)setFace(Number(button.dataset.face));};$('prev-face').onclick=()=>setFace(face-1);$('next-face').onclick=()=>setFace(face+1);
function setMode(next){mode=next;document.body.classList.toggle('is-solving',mode==='solution');updateGuide();$('setup-panel').hidden=mode!=='setup';$('solution-panel').hidden=mode!=='solution';$('edit-tab').classList.toggle('active',mode==='setup');$('solve-tab').classList.toggle('active',mode==='solution');save();}
$('edit-tab').onclick=()=>{if(busy||solving)return;playing=false;setMode('setup');renderSetup();status('Edit the current cube, then find a new solution.');};$('solve-tab').onclick=()=>{if(solving||busy)return;if(moves.length){setMode('solution');renderSolution();}else $('solve').click();};
function fitCamera(){if(!camera)return;const distance=11.9/Math.min(1,Math.max(.35,camera.aspect));camera.position.setLength(distance);controls.update();}
function resetView(){if(!camera)return;camera.position.set(6.8,5.5,8.1);controls.target.set(0,0,0);fitCamera();} $('reset-view').onclick=resetView;
$('scramble').onclick=()=>{if(busy||solving)return;state=Cube.random().asString();moves=[];step=0;playing=false;buildCube();renderSetup();save();status('A fresh scramble. Solve it to try the full experience.');};
$('clear').onclick=()=>{if(busy||solving)return;state=SOLVED;moves=[];step=0;buildCube();renderSetup();save();status('Reset to a solved cube. Paint the squares to match yours.');};
function revealSolution(){if(matchMedia('(max-width:850px)').matches)requestAnimationFrame(()=>$('solution-panel').scrollIntoView({block:'start',behavior:reduced?'instant':'smooth'}));}
function unlock(){solving=false;$('solve').disabled=false;$('solve').innerHTML=`Find my solution ${icon('arrow-up-right')}`;renderSetup();}
$('solve').onclick=()=>{if(solving||busy)return;const error=validate(state,Cube);if(error){status(error,true);return;}original=state;playing=false;if(state===SOLVED){moves=[];step=0;setMode('solution');renderSolution();revealSolution();status('This cube is already solved. Try a scramble or edit your colours.');return;}solving=true;$('solve').disabled=true;$('solve').textContent='Finding your way…';renderSetup();status('Finding a solution on your device…');
 try{if(!worker){worker=new Worker('/tools/rubiks-cube/solver.bundle.js');worker.onmessage=({data})=>{if(data.status){status(data.status);return;}clearTimeout(timeout);unlock();if(data.error){status(data.error,true);return;}moves=data.algorithm.trim().split(/\s+/).filter(Boolean);step=0;setMode('solution');resetView();renderSolution();revealSolution();status(`${moves.length} moves to clarity. Follow the next turn below.`);};worker.onerror=()=>{clearTimeout(timeout);worker.terminate();worker=null;unlock();status('The solver could not load. Please reload and try again.',true);};}worker.postMessage({state});timeout=setTimeout(()=>{worker.terminate();worker=null;unlock();status('This solve took too long. Your colours are saved; please try again.',true);},60000);}catch{unlock();status('This browser could not start the solver. Please try a current browser.',true);}};
function updateGuide(){if(!scene)return;if(guide){scene.remove(guide);guide.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});guide=null;}if(mode!=='solution'||step>=moves.length||busy)return;
 guide=new THREE.Group();const move=moves[step],normal=new THREE.Vector3(...NORMALS[move[0]]);guide.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);guide.position.copy(normal.multiplyScalar(1.56));
 const points=[[-1.53,-1.53,0],[1.53,-1.53,0],[1.53,1.53,0],[-1.53,1.53,0]].map(p=>new THREE.Vector3(...p));guide.add(new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xd6ed99,transparent:true,opacity:.75})));
 const clockwise=!move.endsWith("'");const curve=[];for(let i=0;i<=35;i++){const a=(clockwise?-1:1)*i/35*Math.PI*.68+Math.PI*.65;curve.push(new THREE.Vector3(Math.cos(a)*1.84,Math.sin(a)*1.84,.03));}guide.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve),new THREE.LineBasicMaterial({color:0xd6ed99})));const tip=new THREE.Mesh(new THREE.ConeGeometry(.075,.22,12),new THREE.MeshBasicMaterial({color:0xd6ed99}));tip.position.copy(curve.at(-1));tip.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),curve.at(-1).clone().sub(curve.at(-2)).normalize());guide.add(tip);scene.add(guide);
}
function renderSolution(){updateGuide();const done=step>=moves.length;const move=moves[step];$('move-count').textContent=done?'ALL SIDES, IN HARMONY':`NEXT · MOVE ${String(step+1).padStart(2,'0')} OF ${moves.length}`;$('move-symbol').innerHTML=done?icon('check'):move.replace("'",'′');$('move-description').textContent=done?'You’ve brought it all together.':`Turn the ${LABELS[move[0]].toLowerCase()} face ${move.endsWith('2')?'180°':move.endsWith("'")?'counterclockwise':'clockwise'}.`;$('solution-title').textContent=done?'Hello, clarity.':'Your way to solved.';$('move-perspective').textContent=done?'Every face is complete. Nicely done.':'Clockwise is viewed looking directly at that face.';$('progress').style.width=`${moves.length?step/moves.length*100:100}%`;$('play').innerHTML=playing?`${icon('pause')}<span>Pause</span>`:`${icon('play')}<span>Play solution</span>`;$('play').disabled=done;$('previous').disabled=step===0||busy;$('next').disabled=done||busy;$('restart').disabled=busy||step===0;$('move-list').innerHTML=moves.map((m,i)=>`<span class="${i<step?'done':i===step?'current':''}" ${i===step?'aria-current="step"':''}>${i+1}. ${m.replace("'",'′')}</span>`).join('');}
function animateMove(move){if(guide)guide.visible=false;return new Promise(resolve=>{if(!renderer||!root){state=Cube.fromString(state).move(move).asString();resolve();return;}const group=new THREE.Group();root.add(group);const axis=new THREE.Vector3(...NORMALS[move[0]]);cubies.filter(c=>new THREE.Vector3(...c.userData.pos).dot(axis)>.5).forEach(c=>group.attach(c));activeTurn={group,axis,angle:-Math.PI/2*(move.endsWith('2')?2:move.endsWith("'")?-1:1),start:performance.now(),duration:reduced?1:Number($('speed').value),finish:()=>{state=Cube.fromString(state).move(move).asString();buildCube();resolve();}};});}
async function advance(direction){if(busy||solving||direction===1&&step>=moves.length||direction===-1&&step<=0)return;busy=true;renderSolution();await animateMove(direction===1?moves[step]:inverse(moves[step-1]));step+=direction;busy=false;if(step===moves.length)playing=false;renderSolution();save();if(playing)setTimeout(()=>{if(playing)advance(1);},reduced?600:350);}
$('next').onclick=()=>{playing=false;advance(1);};$('previous').onclick=()=>{playing=false;advance(-1);};$('play').onclick=()=>{playing=!playing;renderSolution();if(playing&&!busy)advance(1);};$('restart').onclick=()=>{if(busy)return;playing=false;state=original;step=0;buildCube();renderSolution();save();status('Back at the beginning. Keep white on top and green in front.');};
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;renderSolution();}});
$('help').onclick=()=>$('help-dialog').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
// Local photo assistance: user-aligned crop with robust median patch samples.
let photo=null,photoRotation=0,offset=[0,0];const canvas=$('scan-canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
$('photo-mode').onclick=()=>{if(solving)return;$('scan-instructions').textContent=`${LABELS[FACES[face]]} face (${NAMES[FACES[face]]}). ${hints[FACES[face]]} Photograph straight-on in even light.`;$('scan-dialog').showModal();};$('manual-mode').onclick=()=>$('face-grid').querySelector('button:not(:disabled)').focus();
function drawPhoto(){if(!photo)return;ctx.fillStyle='#111811';ctx.fillRect(0,0,480,480);const rotated=photoRotation%2;const w=rotated?photo.height:photo.width,h=rotated?photo.width:photo.height;const scale=Math.min(480/w,480/h)*Number($('crop-zoom').value);ctx.save();ctx.translate(240+offset[0],240+offset[1]);ctx.rotate(photoRotation*Math.PI/2);ctx.drawImage(photo,-photo.width*scale/2,-photo.height*scale/2,photo.width*scale,photo.height*scale);ctx.restore();}
$('photo').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>25*1024*1024){status('Choose a photo smaller than 25 MB.',true);$('scan-dialog').close();return;}try{if(photo)photo.close();photo=await createImageBitmap(file);photoRotation=0;offset=[0,0];$('crop-zoom').value='1';$('scan-placeholder').hidden=true;$('import-photo').disabled=false;$('rotate-photo').disabled=false;drawPhoto();}catch{status('This photo format could not be opened. Please use JPG, PNG, or WebP.',true);$('scan-dialog').close();}};
$('crop-zoom').oninput=drawPhoto;$('rotate-photo').onclick=()=>{photoRotation++;offset=[0,0];drawPhoto();};let drag;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,...offset];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const scale=480/canvas.clientWidth;offset=[drag[2]+(e.clientX-drag[0])*scale,drag[3]+(e.clientY-drag[1])*scale];drawPhoto();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
function classify(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min,s=max?delta/max:0;if(s<.23)return'U';let h=delta===0?0:max===r?((g-b)/delta)%6:max===g?(b-r)/delta+2:(r-g)/delta+4;h=(h*60+360)%360;if(h<13||h>335)return'R';if(h<43)return'L';if(h<78)return'D';if(h<175)return'F';return'B';}
$('import-photo').onclick=()=>{if(!photo)return;const chars=state.split('');for(let r=0;r<3;r++)for(let c=0;c<3;c++){if(r===1&&c===1)continue;const x=48+(c+.5)*128,y=48+(r+.5)*128;const data=ctx.getImageData(x-9,y-9,18,18).data;const channels=[[],[],[]];for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)channels[k].push(data[i+k]);const rgb=channels.map(a=>a.sort((a,b)=>a-b)[Math.floor(a.length/2)]);chars[face*9+r*3+c]=classify(...rgb);}state=chars.join('');moves=[];step=0;buildCube();renderSetup();save();$('scan-dialog').close();status(`Photo colours added to ${LABELS[FACES[face]].toLowerCase()}. Review all eight squares, then continue to the next face.`);};
init3d();renderSetup();setMode(mode);renderSolution();if(state!==SOLVED)status('Your cube is here, right where you left it.');
