import test from 'node:test';
import assert from 'node:assert/strict';
import {traction,longitudinal,steeringMotion,VEHICLE_DYNAMICS} from '../../evermile/handling.js';
function stopping(vehicle,rain){let speed=27.78,d=0;const mu=traction({vehicle,rain});for(let i=0;i<24000&&speed>.25;i++){const a=longitudinal({vehicle,speed,brake:1,mu,hold:true});speed=Math.max(0,speed+a/120);d+=speed/120;}assert.ok(speed<=.25);return d;}
test('Wet and icy roads offer less tire grip than dry asphalt',()=>{assert.ok(traction({rain:1})<traction({rain:0}));assert.ok(traction({snow:true})<traction({rain:1}));assert.ok(traction({offroad:true})<traction({}));});
test('100 km/h stopping distance grows in rain; coach stops more slowly',()=>{const dry=stopping('coupe',0),wet=stopping('coupe',1),bus=stopping('coach',0);assert.ok(dry>30&&dry<50,`dry ${dry}`);assert.ok(wet>dry*1.25,`wet ${wet}`);assert.ok(bus>dry,`bus ${bus}`);console.log({dryMetres:dry.toFixed(1),wetMetres:wet.toFixed(1),coachMetres:bus.toFixed(1)});});
test('Vehicle wheelbase affects low-speed turning; tire budget limits high-speed turns',()=>{for(const vehicle of Object.keys(VEHICLE_DYNAMICS)){let rate=0;for(let i=0;i<600;i++)rate=steeringMotion({vehicle,speed:45,steer:.4,mu:.6,previousRate:rate,dt:1/120}).yawRate;assert.ok(Math.abs(rate*45)<=.6*9.81+.01);}const car=steeringMotion({speed:3,steer:.2,mu:1,dt:1,vehicle:'coupe'});const bus=steeringMotion({speed:3,steer:.2,mu:1,dt:1,vehicle:'coach'});assert.ok(bus.yawRate<car.yawRate);});
test('Brake reverses manually after stop; automation and parking brake hold stationary',()=>{assert.ok(longitudinal({speed:0,brake:1})<0);assert.equal(longitudinal({speed:0,brake:1,hold:true}),0);assert.equal(longitudinal({speed:0,brake:1,parking:true}),0);assert.ok(longitudinal({speed:-3,parking:true})>0);});
test('Long runs remain finite for all vehicles and traction conditions',()=>{for(const vehicle of Object.keys(VEHICLE_DYNAMICS))for(const rain of [0,1]){let speed=0,rate=0;const mu=traction({vehicle,rain});for(let i=0;i<120*60;i++){const throttle=i<3600?1:0,brake=i>=3600?1:0,a=longitudinal({vehicle,speed,throttle,brake,mu});speed=Math.max(-9,Math.min(65,speed+a/120));rate=steeringMotion({vehicle,speed,steer:Math.sin(i*.01)*.4,mu,acceleration:a,previousRate:rate,dt:1/120}).yawRate;assert.ok(Number.isFinite(speed)&&Number.isFinite(rate));}}});
