(() => {
  'use strict';
  // Side-by-side GCC country comparison. Data comes from /gcc/compare-data.json (generated by scripts/gcc/gen.py).
  const out = document.getElementById('gc-sw-out');
  if (!out) return;
  const FIELDS = [['platforms_short', 'Key platforms'], ['language_short', 'Language'], ['weekend', 'Weekend'], ['currency', 'Currency'], ['law_short', 'Data law'], ['peak', 'Peak moments']];
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const pick = { a: 'Oman', b: 'Saudi Arabia' };
  let data = null;
  function render() {
    document.querySelectorAll('.gc-sw-btns').forEach((g) => g.querySelectorAll('button').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.c === pick[g.dataset.side]))));
    if (!data) return;
    const A = data[pick.a], B = data[pick.b];
    out.innerHTML = `<div class="gc-sw-row gc-sw-head"><span></span><span>${A.flag} ${esc(A.name)}</span><span>${B.flag} ${esc(B.name)}</span></div>` +
      FIELDS.map(([k, label]) => `<div class="gc-sw-row${A[k] === B[k] ? ' gc-sw-same' : ''}"><span>${label}</span><span>${esc(A[k])}</span><span>${esc(B[k])}</span></div>`).join('') +
      `<div class="gc-sw-row"><span>Full guide</span><span><a href="${A.link}">${esc(A.name)} guide →</a></span><span><a href="${B.link}">${esc(B.name)} guide →</a></span></div>`;
  }
  document.querySelectorAll('.gc-sw-btns').forEach((g) => g.addEventListener('click', (e) => {
    const b = e.target.closest('button[data-c]');
    if (!b) return;
    pick[g.dataset.side] = b.dataset.c;
    render();
  }));
  render();
  fetch('/gcc/compare-data.json').then((r) => r.json()).then((d) => { data = d; render(); }).catch(() => { out.textContent = 'Comparison data could not be loaded. See the table below.'; });
})();
