import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {DRACOLoader} from './vendor/loaders/DRACOLoader.js';
const draco=new DRACOLoader().setDecoderPath('./vendor/draco/').setWorkerLimit(1);
const modelLoader=new GLTFLoader().setDRACOLoader(draco);
function block(w,h,d,r=.07){const shape=new T.Shape();const x=-w/2,y=-h/2;shape.moveTo(x+r,y);shape.lineTo(x+w-r,y);shape.quadraticCurveTo(x+w,y,x+w,y+r);shape.lineTo(x+w,y+h-r);shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h);shape.lineTo(x+r,y+h);shape.quadraticCurveTo(x,y+h,x,y+h-r);shape.lineTo(x,y+r);shape.quadraticCurveTo(x,y,x+r,y);const g=new T.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelThickness:r*.5,bevelSize:r*.4,bevelSegments:4,steps:1,curveSegments:3});g.translate(0,0,-d/2);g.computeVertexNormals();return g}
function wedge(w,baseY,topY,zBack,zFront,topBack,topFront){const p=[-w,baseY,zBack,w,baseY,zBack,w,baseY,zFront,-w,baseY,zFront,-w*.84,topY,topBack,w*.84,topY,topBack,w*.84,topY,topFront,-w*.84,topY,topFront];const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex([0,2,1,0,3,2,4,5,6,4,6,7,0,1,5,0,5,4,1,2,6,1,6,5,2,3,7,2,7,6,3,0,4,3,4,7]);const ix=g.index;for(let i=0;i<ix.count;i+=3){const a=ix.getX(i);ix.setX(i,ix.getX(i+2));ix.setX(i+2,a)}g.computeVertexNormals();return g}
export class Vehicle{
 constructor(scene,type='coupe',color='#e9e7db'){this.scene=scene;this.group=new T.Group();scene.add(this.group);this.wheels=[];this.frontWheels=[];this.type=type;this.body=new T.MeshPhysicalMaterial({color,metalness:.45,roughness:.25,clearcoat:1,clearcoatRoughness:.16});this.glass=new T.MeshPhysicalMaterial({color:0x263c49,metalness:.65,roughness:.12,clearcoat:1});this.black=new T.MeshStandardMaterial({color:0x151b1d,roughness:.65});this.chrome=new T.MeshStandardMaterial({color:0xadb6ba,metalness:.9,roughness:.2});this.rubber=new T.MeshStandardMaterial({color:0x171c1e,roughness:.94});this.red=new T.MeshStandardMaterial({color:0x610b12,emissive:0xb92723,emissiveIntensity:.65,roughness:.25});this.white=new T.MeshStandardMaterial({color:0xeaf1ea,emissive:0xe6f8ff,emissiveIntensity:1});this.build();if(type==='coupe')this.loadDetailedCar();}
 add(g,m,x,y,z,parent=this.group){const mesh=new T.Mesh(g,m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
 wheel(x,z,r=.39){const wheel=new T.Group();wheel.position.set(x,r,z);this.group.add(wheel);this.wheels.push(wheel);if(z>0)this.frontWheels.push(wheel);const tire=this.add(new T.CylinderGeometry(r,r,.26,24),this.rubber,0,0,0,wheel);tire.rotation.z=Math.PI/2;const outer=x>0?.145:-.145;const hub=this.add(new T.CylinderGeometry(r*.68,r*.68,.015,24),this.chrome,outer,0,0,wheel);hub.rotation.z=Math.PI/2;const dark=this.add(new T.CylinderGeometry(r*.52,r*.52,.02,20),this.black,outer*1.06,0,0,wheel);dark.rotation.z=Math.PI/2;for(let i=0;i<5;i++){const a=i*Math.PI*2/5;const spoke=this.add(new T.BoxGeometry(.03,r*.98,.05),this.chrome,outer*1.15,0,0,wheel);spoke.rotation.x=a;}return wheel}
 build(){const coach=this.type==='coach',bike=this.type==='bike';if(bike){this.add(block(.55,.7,2),this.body,0,.73,0);this.add(block(.42,.2,1.1),this.black,0,1.2,-.3);this.add(wedge(.3,.95,1.65,.2,.85,.3,.45),this.glass,0,0,0);this.wheel(0,1,.43);this.wheel(0,-1,.43);this.add(block(1.05,.065,.12,.02),this.chrome,0,1.25,.52);this.add(block(.25,.15,.1,.025),this.white,0,1.03,1.03);this.add(block(.22,.1,.1,.02),this.red,0,1,-1.07);}
 else if(coach){this.add(block(2.5,2.8,7.6,.2),this.body,0,1.84,0);this.add(block(2.46,1.1,7.42,.1),this.glass,0,2.53,.04);this.add(block(2.25,.12,7.2,.06),this.body,0,3.32,0);for(let z=-2.8;z<3.1;z+=1.1)this.add(new T.BoxGeometry(2.5,1.12,.045),this.body,0,2.52,z);this.add(new T.BoxGeometry(2.4,.65,.05),this.black,0,1.85,3.79);for(const x of [-1.2,1.2]){this.wheel(x,2.48,.52);this.wheel(x,-2.42,.52);}for(const x of [-.9,.9]){this.add(block(.45,.16,.1),this.white,x,.8,3.86);this.add(block(.16,.45,.1),this.red,x,1,-3.86);}}
 else{this.add(block(1.94,.49,4.1,.13),this.body,0,.78,0);this.add(block(1.88,.29,3.75,.1),this.black,0,.48,-.08);this.add(wedge(.88,.98,1.68,-1.44,.96,-.85,.24),this.glass,0,0,0);this.add(block(1.48,.075,1.06,.04),this.body,0,1.69,-.33);this.add(block(1.75,.13,1.05,.04),this.body,0,1.02,1.48);this.add(block(1.73,.17,.59,.06),this.body,0,1.03,-1.75);for(const x of [-.85,.85]){this.add(block(.035,.56,.06,.01),this.body,x,1.32,-.57);this.add(block(.22,.12,.3,.04),this.body,x*1.25,1.17,.45);this.add(block(.5,.1,.08,.025),this.white,x*.81,.9,2.1);this.add(block(.66,.1,.07,.025),this.red,x*.70,.96,-2.13);}this.add(block(1.65,.16,.06,.04),this.black,0,.54,2.12);this.add(block(1.66,.18,.07,.04),this.black,0,.47,-2.11);const plate=new T.MeshStandardMaterial({color:0xdedfcf});this.add(block(.48,.13,.035,.015),plate,0,.69,-2.16);this.add(new T.TorusGeometry(.055,.013,6,20),this.chrome,0,.99,-2.19);for(const x of [-.98,.98]){this.wheel(x,1.31);this.wheel(x,-1.31);}}
 this.makeInterior();this.headlights=[];for(const x of [-.65,.65]){const light=new T.SpotLight(0xe4f4ff,0,125,.42,.55,1.2);light.position.set(bike?x*.3:x,.85,coach?3.7:2);light.target.position.set(x,.1,60);this.group.add(light,light.target);this.headlights.push(light);}
 }
 makeInterior(){this.interior=new T.Group();this.group.add(this.interior);this.interior.visible=false;const bike=this.type==='bike',coach=this.type==='coach';this.seatY=coach?2.63:bike?1.73:1.43;this.seatZ=coach?2.4:bike?-.1:-.05;const dashY=this.seatY-.38,dashZ=this.seatZ+1.12;this.add(block(bike?.7:2,.16,.55,.07),this.black,0,dashY,dashZ,this.interior);const screen=document.createElement('canvas');screen.width=512;screen.height=160;this.dashboardCanvas=screen;this.dashboardTexture=new T.CanvasTexture(screen);this.dashboardTexture.colorSpace=T.SRGBColorSpace;this.screenMesh=this.add(new T.PlaneGeometry(.61,.19),new T.MeshBasicMaterial({map:this.dashboardTexture}),.40,dashY+.055,dashZ-.29,this.interior);this.screenMesh.rotation.y=Math.PI;this.screenMesh.rotation.x=.18;const steering=new T.Group();steering.position.set(.4,dashY-.015,dashZ-.53);this.interior.add(steering);this.steering=steering;const rim=this.add(new T.TorusGeometry(.20,.026,10,32),this.black,0,0,0,steering);const core=this.add(block(.15,.1,.03,.015),this.black,0,-.025,0,steering);for(const a of [0,2.1,4.2]){const bar=this.add(new T.BoxGeometry(.023,.17,.025),this.chrome,Math.sin(a)*.07,Math.cos(a)*.07,0,steering);bar.rotation.z=-a;}this.updateDashboard(0,0,false);}
 updateDashboard(speed,distance,auto){const ctx=this.dashboardCanvas.getContext('2d');ctx.fillStyle='#111c21';ctx.fillRect(0,0,512,160);ctx.strokeStyle='#82d9db';ctx.lineWidth=5;ctx.beginPath();ctx.arc(88,80,54,.7*Math.PI,2.3*Math.PI);ctx.stroke();ctx.fillStyle='#eaf4ee';ctx.font='50px sans-serif';ctx.textAlign='center';ctx.fillText(String(Math.round(Math.abs(speed))),88,91);ctx.font='13px monospace';ctx.fillStyle='#8ca7a7';ctx.fillText('KM/H',88,118);ctx.textAlign='left';ctx.font='20px monospace';ctx.fillStyle='#d7e5d3';ctx.fillText(distance.toFixed(1).padStart(7,'0')+' km',180,63);ctx.font='14px monospace';ctx.fillStyle=auto?'#dcefa9':'#9aadb5';ctx.fillText(auto?'◉  AUTODRIVE':'D   ELECTRIC',182,98);this.dashboardTexture.needsUpdate=true;}
 update(dt,speed,steer,night,braking,firstPerson){if(this.detailed){for(const item of this.realWheels){item.object.quaternion.copy(item.base);if(item.front)item.object.rotateY(steer);item.object.rotateX(this.wheelAngle||0);}this.wheelAngle=(this.wheelAngle||0)-speed*dt/.34;for(const mat of this.realBrakeMats)mat.emissiveIntensity=braking?2.4:.45;this.detailed.visible=!firstPerson;}for(const wheel of this.wheels){for(const part of wheel.children)part.rotation.x+=speed*dt/.39;}for(const wheel of this.frontWheels)wheel.rotation.y=steer;this.red.emissiveIntensity=braking?4:.7;this.white.emissiveIntensity=night?3:1;for(const light of this.headlights)light.intensity=night?100:0;this.interior.visible=firstPerson;this.steering.rotation.z=-steer*3.5;for(const child of this.group.children){if(child.userData.fallback)child.visible=!this.detailed&&!firstPerson;else if(child.isMesh)child.visible=!firstPerson;} }

 loadDetailedCar(){
  modelLoader.load('./assets/sports-coupe.glb',gltf=>{
   if(this.disposed){gltf.scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()});return;}
   const model=gltf.scene;model.rotation.y=Math.PI;model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model);const center=box.getCenter(new T.Vector3());model.position.x=-center.x;model.position.z=-center.z;model.position.y=-box.min.y;
   this.detailed=model;this.realWheels=[];this.realFront=[];this.realBrakeMats=[];
   model.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;if(o.material){o.material.envMapIntensity=.75;o.material.metalness=Math.min(o.material.metalness,.35);if(/glass/i.test(o.name)){o.material=new T.MeshPhysicalMaterial({color:0xa5c5d2,metalness:.1,roughness:.08,transparent:true,opacity:.43,depthWrite:false,clearcoat:1,side:T.DoubleSide});}if(/lights_red|brakes/.test(o.name)){o.material=new T.MeshStandardMaterial({color:0x8b0710,emissive:0xff1c12,emissiveIntensity:.5,roughness:.23});this.realBrakeMats.push(o.material);}if(o.name==='leds')o.material=new T.MeshStandardMaterial({color:0xffffff,emissive:0xe2efff,emissiveIntensity:1.6});if(/rim_|chrome/.test(o.name))o.material=new T.MeshStandardMaterial({color:0xbdc4c7,metalness:.95,roughness:.2});}});
   const body=model.getObjectByName('body');if(body)body.material=this.body;this.body.metalness=.65;this.body.roughness=.24;this.body.envMapIntensity=.85;this.body.clearcoat=1;
   for(const name of ['wheel_fl','wheel_fr','wheel_rl','wheel_rr']){const wheel=model.getObjectByName(name);if(wheel){this.realWheels.push({object:wheel,base:wheel.quaternion.clone(),front:name==='wheel_fl'||name==='wheel_fr'});}}
   for(const o of this.group.children){if(o!==this.interior&&!o.isLight&&!o.isObject3DTarget)o.userData.fallback=true;}
   this.group.add(model);this.interior.position.y=-.31;this.seatY=1.12;this.seatZ=-.05;
   document.dispatchEvent(new CustomEvent('vehicleloaded',{detail:{name:'Sports coupé',source:'vicent091036 / Three.js'}}));
  },undefined,error=>{console.error('Detailed vehicle load failed',error);document.dispatchEvent(new CustomEvent('vehicleloaderror'));});
 }
 setColor(color){this.body.color.set(color)}
 dispose(){this.disposed=true;this.scene.remove(this.group);const geos=new Set(),mats=new Set();this.group.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)mats.add(o.material)});for(const g of geos)g.dispose();for(const m of mats)m.dispose();this.dashboardTexture.dispose();}
}
