import * as T from './vendor/three.module.js';
import {createRoad,random,noise,lerp,smooth} from './math.js?v=20260926b';
import {Scenery} from './scenery.js?v=20260926c';
const scratch=new T.Object3D(),col=new T.Color();
const CHUNK=240;
const TERRAIN_COLUMNS=[-850,-620,-420,-290,-200,-135,-85,-55,-32,-19,-11,-6.1,-5.5,0,5.5,6.1,11,19,32,55,85,135,200,290,420,620,850];
export const THEMES={summer:{ground:0x8c9e56,tree:0x5f8a4a,horizon:0xc4d6dc,sky:0x6495c5},spring:{ground:0x7da555,tree:0x5a8249,horizon:0xd2e3e0,sky:0x86b7d9},autumn:{ground:0x8b794c,tree:0xa46930,horizon:0xd6c9ad,sky:0x8dabb9},winter:{ground:0xd7dedd,tree:0x788c82,horizon:0xd6e0e6,sky:0x8faecb},mars:{ground:0x977151,tree:0x795841,horizon:0xd0b090,sky:0x857969},moon:{ground:0x878c91,tree:0x777777,horizon:0x303845,sky:0x050a14},venus:{ground:0xa89053,tree:0x967945,horizon:0xdbbc72,sky:0x998045}};
function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),rng=random(kind==='road'?717:9);ctx.fillStyle=kind==='road'?'#6f7271':'#dcd7c3';ctx.fillRect(0,0,512,512);for(let i=0;i<45000;i++){const v=Math.floor(85+rng()*100);ctx.fillStyle=`rgba(${v},${v},${v},${kind==='road'?.3:.13})`;const r=rng()*2+.3;ctx.fillRect(rng()*512,rng()*512,r,r)}if(kind!=='road'){for(let i=0;i<68000;i++){const x=rng()*512,y=rng()*512;ctx.strokeStyle=rng()>.5?'#77775c40':'#faf2cc60';ctx.lineWidth=.4+rng()*.7;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+2+rng()*4,y-2-rng()*7);ctx.stroke();}}if(kind==='road'){ctx.fillStyle='#e0e0cd';ctx.fillRect(12,0,4,512);ctx.fillRect(496,0,4,512);ctx.fillStyle='#e7e7d8';ctx.fillRect(253,18,6,108);ctx.fillRect(253,274,6,108);ctx.fillStyle='#54595722';ctx.fillRect(112,0,45,512);ctx.fillRect(355,0,45,512)}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t}
function foliageTexture(grass=false){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),rand=random(grass?82:53);if(grass){for(let i=0;i<90;i++){const x=rand()*256,h=25+rand()*210,g=ctx.createLinearGradient(0,256,0,256-h),r0=130+rand()*75,g0=135+rand()*70,b0=95+rand()*65;g.addColorStop(0,`rgb(${r0*.5},${g0*.55},${b0*.5})`);g.addColorStop(1,`rgb(${r0},${g0},${b0})`);ctx.strokeStyle=g;ctx.lineWidth=1+rand()*2;ctx.beginPath();ctx.moveTo(x,256);ctx.quadraticCurveTo(x+(rand()-.5)*40,256-h*.65,x+(rand()-.5)*65,256-h);ctx.stroke()}}else{for(let i=0;i<1600;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*105,x=128+Math.cos(a)*r,y=128+Math.sin(a)*r;const shade=1.22-(y/256)*.5-(r/105)*.1,lum=Math.min(255,(92+rand()*125)*shade);ctx.fillStyle=`rgb(${lum*.9},${lum},${lum*.79})`;ctx.beginPath();ctx.ellipse(x,y,2+rand()*5,2+rand()*2,rand()*6,0,Math.PI*2);ctx.fill()}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function pineTexture(){const c=document.createElement('canvas');c.width=256;c.height=512;const ctx=c.getContext('2d'),rand=random(31);ctx.strokeStyle='#3b2a1c';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(128,512);ctx.lineTo(128,30);ctx.stroke();const tiers=22;for(let t=0;t<tiers;t++){const k=t/(tiers-1),y=492-k*460,w=(1-k)*112+12;for(const side of [-1,1]){const reach=w*(.85+rand()*.25);const clumps=Math.floor(reach*.9)+6;for(let i=0;i<clumps;i++){const u=Math.pow(rand(),.8),bx=128+side*reach*u,by=y+reach*.3*u*u-rand()*14*(1-u*.5),r=(9+rand()*10)*(1-u*.45);const lum=55+rand()*55,lit=by<y-4?1.25:.9;ctx.fillStyle=`rgb(${lum*.42*lit|0},${lum*.72*lit|0},${lum*.46*lit|0})`;ctx.beginPath();for(let n=0;n<9;n++){const a=n/9*Math.PI*2,rr=r*(.55+rand()*.55);const px=bx+Math.cos(a)*rr,py=by+Math.sin(a)*rr*.55;n?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.fill();}}}ctx.globalCompositeOperation='destination-out';for(let i=0;i<260;i++){ctx.beginPath();ctx.arc(rand()*256,rand()*512,1+rand()*2.2,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function roadTexture(){const S=1024,c=document.createElement('canvas');c.width=c.height=S;const ctx=c.getContext('2d'),rng=random(717);ctx.fillStyle='#55585a';ctx.fillRect(0,0,S,S);
 for(let i=0;i<260000;i++){const v=40+rng()*120;ctx.fillStyle=`rgba(${v},${v},${v+3},${.18+rng()*.22})`;const r=rng()*1.8+.4;ctx.fillRect(rng()*S,rng()*S,r,r);}
 for(let i=0;i<5000;i++){ctx.fillStyle=rng()>.5?'rgba(200,196,188,.22)':'rgba(24,24,26,.24)';const r=rng()*1.3+.6;ctx.beginPath();ctx.arc(rng()*S,rng()*S,r,0,6.3);ctx.fill();}
 for(const cx of [.27,.73])for(const o of [-.07,.07]){const g=ctx.createLinearGradient((cx+o-.05)*S,0,(cx+o+.05)*S,0);g.addColorStop(0,'rgba(20,20,22,0)');g.addColorStop(.5,'rgba(20,20,22,.22)');g.addColorStop(1,'rgba(20,20,22,0)');ctx.fillStyle=g;ctx.fillRect((cx+o-.05)*S,0,.1*S,S);}
 for(let i=0;i<5;i++){ctx.fillStyle=`rgba(34,35,37,${.14+rng()*.1})`;const x=rng()*.8*S+.1*S,y=rng()*S,w=(.05+rng()*.12)*S,h=(.04+rng()*.1)*S;ctx.fillRect(x,y,w,h);ctx.strokeStyle='rgba(15,15,15,.22)';ctx.lineWidth=1.5;ctx.strokeRect(x,y,w,h);}
 ctx.strokeStyle='rgba(18,18,20,.55)';for(let i=0;i<14;i++){let x=rng()*S,y=rng()*S;ctx.lineWidth=.8+rng()*1.4;ctx.beginPath();ctx.moveTo(x,y);for(let k=0;k<9;k++){x+=(rng()-.5)*38;y+=rng()*30;ctx.lineTo(x,y);}ctx.stroke();}
 const paint=(x,y,w,h)=>{ctx.fillStyle='#e8e6dc';ctx.fillRect(x,y,w,h);for(let i=0;i<w*h/10;i++){ctx.fillStyle='rgba(70,70,72,.55)';ctx.fillRect(x+rng()*w,y+rng()*h,1.5,1.5);}};
 paint(22,0,11,S);paint(S-33,0,11,S);paint(S/2-6,40,12,380);paint(S/2-6,552,12,380);
 const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t}
function foliageGeometry(grass=false){const positions=[],uv=[],indices=[];for(let i=0;i<3;i++){const a=i*Math.PI/3,dx=Math.cos(a),dz=Math.sin(a),n=i*4;positions.push(-dx,-1,-dz,dx,-1,dz,dx,1,dz,-dx,1,-dz);uv.push(0,0,1,0,1,1,0,1);indices.push(n,n+1,n+2,n,n+2,n+3)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();if(grass)g.scale(.55,.4,.55);return g;}
export class World{
 constructor(scene,settings){this.scene=scene;this.settings=settings;this.chunks=new Map();this.road=createRoad(settings.seed,settings.roadStyle);this.groundTexture=texture('ground');this.roadTexture=roadTexture();this.groundMat=new T.MeshStandardMaterial({vertexColors:true,map:this.groundTexture,bumpMap:this.groundTexture,bumpScale:.25,roughness:1});this.roadMat=new T.MeshStandardMaterial({map:this.roadTexture,bumpMap:this.roadTexture,bumpScale:.6,roughness:.88,metalness:.02});this.trunkMat=new T.MeshStandardMaterial({color:0x5c5140,roughness:1});this.leafMat=new T.MeshStandardMaterial({map:foliageTexture(),alphaTest:.45,color:0xffffff,roughness:.98,side:T.DoubleSide});this.rockMat=new T.MeshStandardMaterial({color:0x868477,roughness:1});this.postMat=new T.MeshStandardMaterial({color:0x7b7f84,metalness:.6,roughness:.5});this.railMat=new T.MeshStandardMaterial({color:0xc8ccd0,metalness:.85,roughness:.32});this.pineMat=new T.MeshStandardMaterial({map:pineTexture(),alphaTest:.42,color:0xffffff,roughness:.97,side:T.DoubleSide});this.markerMat=new T.MeshStandardMaterial({color:0xf2f2ec,roughness:.6});this.reflectorMat=new T.MeshStandardMaterial({color:0xffb020,emissive:0x8a4a00,emissiveIntensity:.5,roughness:.3,metalness:.2});this.grassMat=new T.MeshStandardMaterial({map:foliageTexture(true),alphaTest:.4,color:0xffffff,side:T.DoubleSide,roughness:1});this.geos={trunk:new T.CylinderGeometry(.13,.22,1,5),leaves:foliageGeometry(),pine:new T.ConeGeometry(1,2.8,7),rock:new T.IcosahedronGeometry(1,1),post:new T.BoxGeometry(.12,1.05,.12),rail:new T.BoxGeometry(.07,.34,6.4),marker:new T.BoxGeometry(.1,1.05,.1),reflector:new T.BoxGeometry(.12,.16,.12),grass:foliageGeometry(true)};this.makeSky();this.scenery=new Scenery(this);this.updatePalette();}
 makeSky(){this.sunDir=new T.Vector3(-.35,.62,.7).normalize();this.moonDir=new T.Vector3(.2,.3,1).normalize();this.lightDir=this.sunDir.clone();
 this.skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color(0x6495c5)},bottom:{value:new T.Color(0xdce7df)},sunDirection:{value:this.sunDir},moonDirection:{value:this.moonDir},sunColor:{value:new T.Color(0xfff6dd)},cloudTint:{value:new T.Color(0xf4f4ef)},cloud:{value:.22},night:{value:0},golden:{value:0},flash:{value:0}},
 vertexShader:`varying vec3 vPosition;void main(){vPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,
 // Sky: height gradient, a sun disc with halo and a warm horizon band at golden hour, a cratered full moon at night, drifting clouds lit by the sun or moon, and stars.
 fragmentShader:`varying vec3 vPosition;uniform vec3 top,bottom,sunDirection,moonDirection,sunColor,cloudTint;uniform float cloud,night,golden,flash;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
 float fbm(vec2 p){return .5*n(p)+.25*n(p*2.1)+.125*n(p*4.3)+.0625*n(p*8.7);}
 void main(){vec3 d=normalize(vPosition);float y=max(d.y,0.);vec3 c=mix(bottom,top,pow(y,.5));
  float sun=max(dot(d,sunDirection),0.),day=1.-night;
  c=mix(c,sunColor*1.08,smoothstep(.3,0.,y)*(.28+.5*pow(sun,2.))*golden*day);
  c+=sunColor*(pow(sun,6.)*.12+pow(sun,40.)*.2)*(.6+golden*.7)*day;
  c=mix(c,bottom*1.04,smoothstep(.2,0.,y)*.3*day*(1.-golden*.6));
  float disc=smoothstep(.99988,.99993,dot(d,sunDirection));
  vec3 sunCore=mix(sunColor,vec3(1.,.96,.88),.55)*(golden>.5?6.:14.);
  vec3 lit=c+sunCore*disc*day+sunColor*pow(sun,1200.)*2.*day;
  float m=max(dot(d,moonDirection),0.);vec3 right=normalize(cross(moonDirection,vec3(0,1,0))),up=cross(right,moonDirection);
  vec2 mp=vec2(dot(d,right),dot(d,up))/.0165;float mr=dot(mp,mp);float onMoon=smoothstep(1.,.92,mr)*step(0.,dot(d,moonDirection));
  float maria=smoothstep(.42,.7,fbm(mp*2.4+7.))*.28+smoothstep(.55,.8,fbm(mp*6.+3.))*.12;
  vec3 moon=vec3(1.,.98,.93)*2.4*(.72+.28*sqrt(max(0.,1.-mr)))*(1.-maria);
  lit=mix(lit,moon,onMoon*night);lit+=vec3(.55,.63,.82)*(pow(m,500.)*.35+pow(m,60.)*.1+pow(m,8.)*.05)*night;
  vec2 uv=d.xz/(max(d.y,.03)+.24)*2.1;float cl=smoothstep(.47,.7,fbm(uv+5.))*smoothstep(.015,.16,y);
  vec3 cloudCol=mix(cloudTint,sunColor*1.2,golden*(.25+.6*pow(sun,2.))*day);cloudCol=mix(cloudCol,vec3(.2,.23,.3)+vec3(.35,.38,.45)*pow(m,6.),night);
  lit=mix(lit,cloudCol,cl*cloud*(1.-night*.35));
  float stars=step(.9984,hash(floor(d.xz/(abs(d.y)+.1)*900.)))*night*smoothstep(0.,.25,y)*(1.-cl*cloud)*(1.-smoothstep(.97,1.,m));
  lit=mix(lit,vec3(.86,.9,1.),flash*.7);gl_FragColor=vec4(lit+stars*.65,1.);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});this.sky=new T.Mesh(new T.SphereGeometry(2400,24,12),this.skyMaterial);this.sky.frustumCulled=false;this.scene.add(this.sky);this.water=new T.Mesh(new T.PlaneGeometry(10000,10000),new T.MeshStandardMaterial({color:0x6e9ca4,roughness:.22,metalness:.55,transparent:true,opacity:.87}));this.water.rotation.x=-Math.PI/2;this.water.position.y=-8;this.scene.add(this.water);this.sky.layers.enable(3);this.water.layers.enable(3);}
 updatePalette(){const s=this.settings;this.theme=THEMES[s.location==='hills'?s.season:s.planet];const night=s.time==='night',sunset=s.time==='sunset',cloudy=s.weather!=='clear',rain=s.weather==='rain';const u=this.skyMaterial.uniforms;u.top.value.set(night?0x050c1e:rain?0x5b6672:sunset?(cloudy?0x6a6a86:0x4c5c8e):this.theme.sky);u.bottom.value.set(night?0x1e2c42:rain?0x98a3a8:sunset?(cloudy?0xd6a88c:0xf2a766):cloudy?0xc3ced0:this.theme.horizon);this.sunDir.set(sunset?-.13:-.35,sunset?.14:.62,sunset?1:.7).normalize();u.sunColor.value.set(sunset?0xff9e4a:0xfff5db);u.cloudTint.value.set(rain?0xb4bcc2:cloudy?0xe4e8ea:0xf4f4ef);u.cloud.value=rain?1:cloudy?.88:sunset?.5:.36;u.night.value=night?1:0;u.golden.value=sunset&&!rain?1:0;this.lightDir.copy(night?this.moonDir:this.sunDir);const fogCol=this.skyMaterial.uniforms.bottom.value;this.scene.fog=new T.Fog(fogCol,rain?90:cloudy?200:420,rain?850:cloudy?1400:1900);this.roadMat.map=s.location==='hills'?this.roadTexture:this.groundTexture;this.roadMat.color.set(s.location==='hills'?(s.season==='winter'?0xa7b1b3:0xffffff):this.theme.ground);this.roadMat.needsUpdate=true;this.water.visible=s.location==='hills';this.scenery?.setMood({night,dusk:sunset||rain,wet:rain||s.season==='winter'||s.season==='spring'});this.water.material.color.set(night?0x203343:sunset?0x958676:0x70979c);}
 makeInstances(group,geo,material,items,shadows=false){if(!items.length)return;const mesh=new T.InstancedMesh(geo,material,items.length);for(let i=0;i<items.length;i++){const p=items[i];scratch.position.set(...p.p);scratch.rotation.set(...(p.r||[0,0,0]));scratch.scale.set(...p.s);scratch.updateMatrix();mesh.setMatrixAt(i,scratch.matrix);if(p.c!==undefined)mesh.setColorAt(i,col.set(p.c));}mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;mesh.castShadow=shadows;mesh.receiveShadow=true;mesh.computeBoundingSphere();group.add(mesh);}
 // Match terrain triangles so vegetation rests on the rendered surface.
 surfaceHeight(x,z,off=false){const r=this.road,z0=Math.floor(z/5)*5,z1=z0+5,t=(z-z0)/5,dx=x-lerp(r.x(z0),r.x(z1),t),cols=TERRAIN_COLUMNS;let j=0;while(j<cols.length-2&&cols[j+1]<dx)j++;const u=(dx-cols[j])/(cols[j+1]-cols[j]);const a=r.terrain(r.x(z0)+cols[j],z0,off),b=r.terrain(r.x(z0)+cols[j+1],z0,off),c=r.terrain(r.x(z1)+cols[j],z1,off),d=r.terrain(r.x(z1)+cols[j+1],z1,off);return u+t<=1?a+(b-a)*u+(c-a)*t:d+(c-d)*(1-u)+(b-d)*(1-t);}
 buildChunk(index){const group=new T.Group();group.userData.index=index;const plan=this.scenery.plan(index,CHUNK);const rng=random(this.road.id+index*331+91),r=this.road,off=this.settings.location!=='hills';const rows=49,columns=TERRAIN_COLUMNS;const pos=[],uv=[],colors=[],indices=[];const base=new T.Color(this.theme.ground),dry=base.clone().multiply(new T.Color(1.22,1.1,.78)),lush=base.clone().multiply(new T.Color(.74,.9,.7)),gravel=new T.Color(this.settings.season==='winter'?0xb9bfc0:0x8a826f),rock=new T.Color(off?0x8a8073:this.settings.season==='winter'?0xaab6b7:0x8b8970);
 for(let i=0;i<rows;i++){const z=index*CHUNK+i*5;for(let j=0;j<columns.length;j++){const x=r.x(z)+columns[j],y=r.terrain(x,z,off);pos.push(x,y,z);uv.push(x/7,z/7);const dx=(r.terrain(x+.8,z,off)-r.terrain(x-.8,z,off))/1.6;const dz=(r.terrain(x,z+.8,off)-r.terrain(x,z-.8,off))/1.6;const slope=Math.sqrt(dx*dx+dz*dz);col.copy(base).lerp(rock,smooth(.6,1.7,slope)*.72);const macro=noise(x*.0065,z*.006,r.id+17);col.lerp(dry,smooth(.55,.85,macro)*.5).lerp(lush,smooth(.45,.15,macro)*.45);const v=.87+noise(x*.029,z*.03,r.id)*.28;col.multiplyScalar(v);const ax=Math.abs(columns[j]);if(!off&&ax<=6.1)col.copy(gravel).multiplyScalar(.9+noise(x*.3,z*.3,r.id)*.2);else if(!off&&ax<=11)col.lerp(lush,.35);colors.push(col.r,col.g,col.b);if(i<rows-1&&j<columns.length-1){const a=i*columns.length+j,b=a+columns.length;indices.push(a,b,a+1,b,b+1,a+1)}}}
 const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.setIndex(indices);geo.computeVertexNormals();const ground=new T.Mesh(geo,this.groundMat);ground.receiveShadow=true;group.add(ground);
 const rp=[],ru=[],ri=[];const width=this.settings.roadWidth/2;for(let i=0;i<rows;i++){const z=index*CHUNK+i*5;for(const side of [-1,1]){rp.push(r.x(z)+side*width,r.y(z)+.055,z);ru.push(side===-1?0:1,z/32)}if(i<rows-1){const a=i*2;ri.push(a,a+2,a+1,a+2,a+3,a+1)}}const rg=new T.BufferGeometry();rg.setAttribute('position',new T.Float32BufferAttribute(rp,3));rg.setAttribute('uv',new T.Float32BufferAttribute(ru,2));rg.setIndex(ri);rg.computeVertexNormals();const road=new T.Mesh(rg,this.roadMat);road.receiveShadow=true;group.add(road);
 const trunks=[],crowns=[],pines=[],rocks=[],posts=[],rails=[],grass=[];const winter=this.settings.season==='winter';const quality=this.settings.quality;const count=off?12:quality==='low'?22:40;
 for(let i=0;i<count;i++){const z=index*CHUNK+rng()*CHUNK,side=rng()>.43?1:-1,x=r.x(z)+side*(12+rng()**1.7*170),y=this.surfaceHeight(x,z,off);if(y<-7||plan.blocked(x,z))continue;const size=3.8+rng()*5.2;if(off){rocks.push({p:[x,y+.4,z],s:[size*.3,size*.17,size*.25],r:[rng(),rng()*6,rng()],c:this.theme.ground});continue;}trunks.push({p:[x,y+size*.43,z],s:[size*.28,size*.86,size*.28]});const evergreen=rng()>.8;if(evergreen){const pc=col.set(winter?0xe4ece9:0xc6d6c0).multiplyScalar(.82+rng()*.3).getHex();const ph=size*(1.05+rng()*.35);pines.push({p:[x,y+ph,z],s:[size*.44,ph,size*.44],r:[0,rng()*6,0],c:pc});}else{for(let k=0;k<7;k++){const a=k*2.399,sx=1.35+rng();col.set(this.theme.tree).multiplyScalar(.78+rng()*.44);crowns.push({p:[x+Math.cos(a)*size*.23,y+size*(.70+rng()*.40),z+Math.sin(a)*size*.23],s:[size*.31*sx,size*.34*sx,size*.31*sx],r:[rng()*.3,rng()*6,rng()*.2],c:col.getHex()});}}}
 for(let i=0;i<26;i++){const z=index*CHUNK+rng()*CHUNK,side=rng()>.5?1:-1,x=r.x(z)+side*(8+rng()*44),y=this.surfaceHeight(x,z,off);if(y>-7&&!plan.blocked(x,z))rocks.push({p:[x,y+.1,z],s:[.3+rng()*1.7,.25+rng(),.4+rng()],r:[rng(),rng()*6,rng()],c:winter&&!off?0xc1cacc:0x827e6c});}
 const railSide=(Math.floor(index/3)%3===0)?1:-1;for(let z=index*CHUNK;z<(index+1)*CHUNK;z+=6){if(!off&&!this.railSide(z)||!off&&!this.railSide(z+6))continue;const x=r.x(z)+railSide*(width+.85),y=r.y(z);posts.push({p:[x,y+.5,z],s:[1,1,1]});const z2=z+3;rails.push({p:[r.x(z2)+railSide*(width+.85),r.y(z2)+.85,z2],s:[1,1,Math.sqrt(1+r.tangent(z2)**2)],r:[-Math.atan((r.y(z2+1)-r.y(z2-1))/2),Math.atan(r.tangent(z2)),0]});}
 const markers=[],reflectors=[];if(!off){for(let z=index*CHUNK+12;z<(index+1)*CHUNK;z+=24){if(!this.railSide(z))continue;const x=r.x(z)-railSide*(width+1.4),y=r.y(z);markers.push({p:[x,y+.5,z],s:[1,1,1]});reflectors.push({p:[x,y+.86,z+.02],s:[1,1,1]});}}this.makeInstances(group,this.geos.marker,this.markerMat,markers,true);this.makeInstances(group,this.geos.reflector,this.reflectorMat,reflectors);
 if(!off&&!winter){const n=quality==='low'?200:quality==='high'?1000:650;for(let i=0;i<n;i++){const z=index*CHUNK+rng()*CHUNK,x=r.x(z)+(rng()>.5?1:-1)*(6+rng()*21),y=this.surfaceHeight(x,z);if(y<-7||plan.blocked(x,z))continue;col.set(this.theme.ground).multiplyScalar(.82+rng()*.4);grass.push({p:[x,y+.25,z],s:[1+rng(),.7+rng()*.7,1+rng()],r:[0,rng()*6,0],c:col.getHex()});}}
 const flowers=[];const spring=this.settings.season==='spring',summer=this.settings.season==='summer';if(!off&&(spring||summer)){const n=Math.round((spring?700:220)*(quality==='low'?.35:quality==='medium'?.7:1));for(let i=0;i<n;i++){const z=index*CHUNK+rng()*CHUNK;if(noise(z*.012,3.7,r.id+29)<(spring?.38:.55))continue;const side=rng()>.5?1:-1,x=r.x(z)+side*(width+1.2+rng()**1.6*9),y=this.surfaceHeight(x,z);if(y<-7||plan.blocked(x,z))continue;const sz=.45+rng()*.35;flowers.push({p:[x,y+sz*.45,z],s:[sz,sz,sz],r:[0,rng()*6,0],c:col.set(0xffffff).multiplyScalar(.85+rng()*.3).getHex()});}}
 group.userData.colliders=[...trunks.map(t=>({x:t.p[0],z:t.p[2],r:t.s[0]*.22+.18})),...rocks.filter(k=>Math.max(k.s[0],k.s[2])>.75).map(k=>({x:k.p[0],z:k.p[2],r:Math.max(k.s[0],k.s[2])*.8}))];
 this.makeInstances(group,this.geos.trunk,this.trunkMat,trunks,true);this.makeInstances(group,this.geos.leaves,this.leafMat,crowns,quality==='high');this.makeInstances(group,this.geos.leaves,this.pineMat,pines,quality==='high');this.makeInstances(group,this.geos.rock,this.rockMat,rocks,true);this.makeInstances(group,this.geos.post,this.postMat,posts,true);this.makeInstances(group,this.geos.rail,this.railMat,rails,true);this.makeInstances(group,this.geos.grass,this.grassMat,grass);this.makeInstances(group,this.geos.grass,this.scenery.flowerMat,flowers);this.scenery.build(group,plan);group.traverse(o=>o.layers.enable(3));this.scene.add(group);this.chunks.set(index,group);
 }
 update(z,camera,immediate=false){this.sky.position.copy(camera.position);const center=Math.floor(z/CHUNK);const back=2,front=this.settings.quality==='low'?5:8;for(const [i,g]of this.chunks){if(i<center-back||i>center+front){this.disposeChunk(g);this.chunks.delete(i)}}let built=0;for(let i=center-back;i<=center+front;i++){if(!this.chunks.has(i)){if(!immediate&&built>=1)break;this.buildChunk(i);built++}}}
 collidersNear(x,z,range){const out=[],c=Math.floor(z/CHUNK);for(let i=c-1;i<=c+1;i++){const g=this.chunks.get(i);if(!g)continue;for(const k of g.userData.colliders||[])if(Math.abs(k.x-x)<range&&Math.abs(k.z-z)<range)out.push(k);}return out;}
 groundHeight(x,z){const r=this.road,d=Math.abs(x-r.x(z)),w=this.settings.roadWidth/2;if(d<=w)return r.y(z)+.055;if(this.settings.location==='hills'){if(d<=w+3.3&&r.townFactor(z)>.02)return r.y(z)+.075;if(d<=w+1.7&&r.bridgeAt(z))return r.y(z)+.25;}return this.surfaceHeight(x,z,this.settings.location!=='hills');}
 // Which side the guard rail runs on here, or 0 where there is none (towns and bridges).
 railSide(z){const r=this.road;if(this.settings.location==='hills'&&(r.townFactor(z)>0||r.bridgeAt(z)||r.bridgeAt(z-8)||r.bridgeAt(z+8)))return 0;return (Math.floor(Math.floor(z/CHUNK)/3)%3===0)?1:-1;}
 disposeChunk(g){this.scene.remove(g);g.traverse(o=>{if(o.userData.shared)return;if(o.isInstancedMesh)o.dispose();else if(o.isMesh)o.geometry.dispose()});}
 rebuild(){for(const g of this.chunks.values())this.disposeChunk(g);this.chunks.clear();this.road=createRoad(this.settings.seed,this.settings.roadStyle);this.updatePalette();}
}
