# Country content for the GCC pages. Facts checked October 2026; Islamic dates are 2027 projections
# confirmed by moon sighting. Keep claims qualitative unless a source is cited in SOURCES.
ISLAMIC = [
  ('~8 Feb', 'Ramadan begins (expected)', 'Evenings become prime time; food, gifting and charity rise.'),
  ('~10 Mar', 'Eid al-Fitr (expected)', 'Peak for fashion, gifts, sweets, salons and short trips.'),
  ('~15–16 May', 'Day of Arafah and Eid al-Adha (expected)', 'Travel, family gatherings and gifting.'),
  ('~6 Jun', 'Islamic New Year 1449 (expected)', 'Public holiday as summer begins.'),
]
MAWLID = ('~14 Aug', 'Prophet’s Birthday (expected)', 'Public holiday in the run-up to back to school.')

C = {
 'uae': dict(
  name='UAE', full='the United Arab Emirates', the='the UAE', ar_name='الإمارات', flag='🇦🇪', accent='fe-teal',
  cities='Dubai, Abu Dhabi, Sharjah and the northern emirates', currency='UAE dirham (AED)', weekend='Saturday–Sunday (since 2022)',
  title='Digital Marketing in the UAE: SEO, Google Ads & Social Guide (2027) | Hisan Ali',
  desc='A practical guide to digital marketing in the UAE: platform mix, Arabic and English content, Dubai and Abu Dhabi search, UAE PDPL rules, 2027 key dates and how to plan campaigns.',
  h1='Digital Marketing in the UAE: <br>A Practical Guide for 2027',
  deck='The UAE is the most international market in the Gulf: dozens of nationalities, English as the working language of business, and some of the most competitive ad auctions in the region. Here is how to plan SEO, Google Ads and social media that actually work there.',
  snapshot=[('Audience','Very international, with large expatriate communities alongside Emiratis. Segment by language and nationality, not only by emirate.'),('Language','English dominates business and search; Arabic matters for Emirati audiences, government-facing work and trust.'),('Competition','Dense and well-funded, especially in Dubai real estate, hospitality, education and e-commerce. Expect higher click costs than elsewhere in the GCC.'),('Buying style','Comparison-heavy. People check reviews, Google Maps and Instagram before they enquire, often on WhatsApp.')],
  platforms=[('Google Search & Maps','The main intent channel. Local searches like “near me” and area names (Dubai Marina, JLT, Khalifa City) matter.'),('Instagram','Discovery and proof for lifestyle, food, beauty, real estate and services.'),('LinkedIn','Unusually strong for B2B and professional services in Dubai and Abu Dhabi.'),('TikTok','Reach for younger audiences and consumer brands; creative must feel native.'),('WhatsApp Business','Where most enquiries turn into conversations and bookings.')],
  language='Most UAE searches for services happen in English, but Arabic searches face far less competition and reach Emirati decision makers. Write Arabic pages for Arabic searches rather than translating English ones, and use Gulf-friendly wording rather than very formal or Levantine phrasing.',
  law=('UAE Personal Data Protection Law (Federal Decree-Law No. 45 of 2021)','Collect consent for tracking and marketing messages, explain data use in a clear privacy policy, and be careful with health and financial data. Free zones such as DIFC and ADGM have their own data protection regimes.'),
  search='Treat each emirate, and in Dubai each major area, as its own local market. A clinic in Abu Dhabi rarely competes with one in Dubai for “near me” searches. Build area pages only where you genuinely serve customers, keep your Google Business Profile accurate, and exclude job-seeker and visa searches in Google Ads.',
  dates=[('3 Nov','UAE Flag Day','National pride content; avoid hard selling.'),('Late Nov','White Friday and 11.11','Heavy discount competition; plan stock and creative early.'),('30 Nov–1 Dec','Commemoration Day','A solemn day of remembrance; pause promotional posts.'),('2–3 Dec','Eid Al Etihad (National Day)','The biggest national moment; patriotic, respectful creative.'),('Dec–Jan','Dubai Shopping Festival','Retail and hospitality peak; dates announced by Visit Dubai.'),('Summer','Dubai Summer Surprises and summer travel','Indoor, delivery and travel offers; many residents travel.'),('Late Aug','Back to school','Uniforms, devices, tuition and transport.')],
  mawlid=True,
  faq=[('Is SEO worth it in the UAE?','Yes, especially for local and niche searches. Broad terms like “Dubai real estate” are fiercely competitive, but specific services, areas and Arabic searches are far more winnable.'),('Should I advertise in Arabic or English in the UAE?','Usually both. English reaches most residents; Arabic reaches Emirati audiences and stands out because fewer advertisers do it well.'),('Do you work with UAE businesses from Oman?','Yes. I work remotely from Muscat with businesses across the GCC, with calls, WhatsApp and clear monthly reporting.'),('Which data protection law applies to marketing in the UAE?','The UAE Personal Data Protection Law (Federal Decree-Law No. 45 of 2021), with separate regimes in some free zones such as DIFC and ADGM. Get legal advice for sensitive data.')]),
 'ksa': dict(
  name='Saudi Arabia', full='the Kingdom of Saudi Arabia', the='Saudi Arabia', ar_name='السعودية', flag='🇸🇦', accent='fe-gold',
  cities='Riyadh, Jeddah, the Eastern Province (Dammam, Khobar) and fast-growing regional cities', currency='Saudi riyal (SAR)', weekend='Friday–Saturday',
  title='Digital Marketing in Saudi Arabia: SEO, Ads & Social Guide (2027) | Hisan Ali',
  desc='Digital marketing in Saudi Arabia explained: Arabic-first content, Snapchat, TikTok and Google, Riyadh and Jeddah search, PDPL rules, Riyadh Season and 2027 key dates.',
  h1='Digital Marketing in Saudi Arabia: <br>Arabic-First, Mobile-First',
  deck='Saudi Arabia is the largest and youngest market in the Gulf, and it rewards brands that speak to it in its own language and on its own platforms. Here is what changes when you plan SEO, ads and social media for the Kingdom.',
  snapshot=[('Audience','A large, young, Saudi-majority population with strong regional differences between Riyadh, Jeddah and the Eastern Province.'),('Language','Arabic-first. English works for some B2B and expatriate audiences, but Arabic content wins most consumer markets.'),('Platforms','Very mobile and video-led. Snapchat and TikTok are central for consumer brands, alongside Google and X.'),('Momentum','Rapid growth in entertainment, tourism and retail creates new seasonal peaks every year.')],
  platforms=[('Google Search & Maps','Essential for services and local intent; most searches are in Arabic.'),('Snapchat','Especially strong with young Saudis; a core channel for consumer brands, not an afterthought.'),('TikTok','Huge reach and discovery; short native video in Saudi Arabic performs best.'),('X (Twitter)','Still important for news, opinion and B2B conversations.'),('Instagram & WhatsApp','Proof, lifestyle content and the conversation that leads to a sale.')],
  language='Write in Arabic first, and in a natural Saudi register for consumer content. Saudi searchers often use different words from other Gulf countries, so research Saudi keywords separately rather than reusing UAE or Omani lists. Formal Modern Standard Arabic suits B2B and government-facing pages.',
  law=('Saudi Personal Data Protection Law (PDPL), enforced by SDAIA','Fully enforceable since 14 September 2024. Get clear consent for marketing, publish an Arabic privacy policy, respect opt-outs and check the rules on transferring data outside the Kingdom.'),
  search='Plan by city. Riyadh, Jeddah and Dammam behave like separate markets with different competitors and vocabulary. Arabic local pages, an accurate Google Business Profile for each branch and Arabic ad copy usually beat English-only campaigns.',
  dates=[('22 Feb','Founding Day','A national celebration of the state’s founding; in 2027 it falls during Ramadan, so tone matters.'),('Summer','Summer travel and seasonal festivals','Domestic tourism and family entertainment.'),('Aug','Back to school','Uniforms, devices and transport.'),('23 Sep','Saudi National Day','The biggest national moment; patriotic campaigns everywhere.'),('From Oct','Riyadh Season','Months of entertainment and events in Riyadh (the 2026 edition opened on 21 October).'),('Late Nov','White Friday and 11.11','Big online sales moments.')],
  mawlid=False,
  faq=[('Which social media platforms matter most in Saudi Arabia?','Snapchat and TikTok are central for consumer brands, with Google for search intent, X for news and B2B, and Instagram and WhatsApp for proof and conversations.'),('Do I need Arabic content for Saudi Arabia?','For most consumer markets, yes. Arabic-first content and ads usually outperform English, and Saudi keyword research should be done separately.'),('What data protection law applies in Saudi Arabia?','The Personal Data Protection Law (PDPL), supervised by SDAIA and fully enforceable since 14 September 2024.'),('Do you work with Saudi businesses?','Yes, remotely from Muscat, with Arabic and English content and clear monthly reporting.')]),
 'qatar': dict(
  name='Qatar', full='the State of Qatar', the='Qatar', ar_name='قطر', flag='🇶🇦', accent='fe-violet',
  cities='Doha and its surrounding municipalities (Al Rayyan, Al Wakrah, Lusail)', currency='Qatari riyal (QAR)', weekend='Friday–Saturday',
  title='Digital Marketing in Qatar: SEO, Ads & Social Guide (2027) | Hisan Ali',
  desc='Digital marketing in Qatar: a compact, high-income Doha market, bilingual content, Google and Instagram, Qatar data protection law, 2027 key dates and campaign planning tips.',
  h1='Digital Marketing in Qatar: <br>A Small Market That Rewards Precision',
  deck='Qatar is compact, wealthy and concentrated around Doha. Audiences are small enough that wasted spend shows quickly, and loyal enough that a strong reputation compounds. Here is how to plan marketing that fits.',
  snapshot=[('Audience','High-income, concentrated in greater Doha, with Qataris and a large international workforce.'),('Language','Bilingual. Arabic for Qatari audiences and trust; English for much of business and the expatriate market.'),('Scale','Small audiences mean frequency caps, fresh creative and careful targeting matter more than big budgets.'),('Reputation','Word of mouth travels fast. Reviews and visible service quality carry real weight.')],
  platforms=[('Google Search & Maps','Primary for services; “near me” and Doha area searches drive local enquiries.'),('Instagram','Strong for lifestyle, food, fashion, real estate and events.'),('Snapchat & TikTok','Reach younger Qatari audiences with native video.'),('LinkedIn','Useful for B2B, energy, construction and professional services.'),('WhatsApp','The default channel for enquiries and bookings.')],
  language='Offer Arabic and English versions of key pages and ads. In a small market, polished Arabic is a visible signal of quality and respect for Qatari customers.',
  law=('Qatar Personal Data Privacy Protection Law (Law No. 13 of 2016)','Obtain consent for electronic marketing, explain data use clearly and secure customer data. Some sectors and the Qatar Financial Centre have additional rules.'),
  search='With fewer competitors per niche, a well-built site and Google Business Profile can rank quickly. In Google Ads, small audiences exhaust fast, so rotate creative and cap frequency on retargeting.',
  dates=[('9 Feb','National Sport Day (second Tuesday of February)','Activity and wellness campaigns; in 2027 it falls right at the start of Ramadan.'),('Summer','Summer travel','Many residents travel; indoor and delivery offers.'),('Late Aug–Sep','Back to school','Uniforms, devices and tuition.'),('Late Nov','White Friday and 11.11','Online sales moments.'),('18 Dec','Qatar National Day','The biggest national moment; patriotic, respectful creative.')],
  mawlid=False,
  faq=[('Is Qatar a good market for digital marketing?','Yes, for businesses that target precisely. Audiences are smaller but high-value, so careful targeting and strong reputation matter more than volume.'),('Should content be in Arabic or English in Qatar?','Both for most businesses: English for much of the market and Arabic for Qatari audiences and credibility.'),('What data law applies to marketing in Qatar?','Qatar’s Personal Data Privacy Protection Law (Law No. 13 of 2016), with extra rules in some sectors and in the Qatar Financial Centre.'),('Do you work with Qatar businesses?','Yes, remotely from Muscat, with regular calls and WhatsApp updates.')]),
 'bahrain': dict(
  name='Bahrain', full='the Kingdom of Bahrain', the='Bahrain', ar_name='البحرين', flag='🇧🇭', accent='fe-teal',
  cities='Manama, Muharraq, Riffa and Seef', currency='Bahraini dinar (BHD)', weekend='Friday–Saturday',
  title='Digital Marketing in Bahrain: SEO, Ads & Social Guide (2027) | Hisan Ali',
  desc='Digital marketing in Bahrain: a compact, connected market, Saudi weekend visitors, bilingual content, Bahrain PDPL, 2027 key dates and practical SEO and ads tips.',
  h1='Digital Marketing in Bahrain: <br>Small Island, Regional Reach',
  deck='Bahrain is small, highly connected and closely tied to Saudi Arabia’s Eastern Province across the causeway. For many businesses, the real audience includes weekend visitors as well as residents. Here is how to plan for both.',
  snapshot=[('Audience','Bahrainis, a large expatriate community and visitors from Saudi Arabia, especially at weekends.'),('Language','Bilingual; Arabic and English both matter, and Saudi visitors respond to Arabic.'),('Geography','Very short distances; a business can serve the whole island, so “Bahrain” searches matter more than city names.'),('Sectors','Strong in financial services, hospitality, retail, F&B and events.')],
  platforms=[('Google Search & Maps','Central for services and restaurants; reviews carry weight.'),('Instagram','The main discovery platform for food, retail and lifestyle.'),('Snapchat & TikTok','Reach younger audiences and Saudi weekend visitors.'),('LinkedIn','Important for finance, fintech and professional services.'),('WhatsApp','Where enquiries and bookings happen.')],
  language='Run Arabic and English versions. If you serve weekend visitors from Saudi Arabia, Arabic creative and targeting of the Eastern Province can open a second market.',
  law=('Bahrain Personal Data Protection Law (Law No. 30 of 2018)','Get consent for direct marketing, provide an easy opt-out, explain data use and protect customer data.'),
  search='Optimise for country-wide searches and key areas like Seef and Juffair, keep Google Business Profile listings accurate, and consider separate campaigns aimed at the Eastern Province for weekend trade.',
  dates=[('Spring','Bahrain Grand Prix (Formula 1)','A major event for hospitality and retail; check the season calendar for the date.'),('Summer','Summer travel','Indoor, delivery and travel offers.'),('Sep','Back to school','Uniforms, devices and transport.'),('Late Nov','White Friday and 11.11','Online sales moments.'),('16–17 Dec','Bahrain National Day','National celebrations; patriotic, respectful creative.')],
  mawlid=True,
  faq=[('How is marketing in Bahrain different from the rest of the GCC?','It is compact and closely connected to Saudi Arabia, so many businesses also market to weekend visitors from the Eastern Province.'),('Do Bahrain businesses need Arabic content?','Usually yes, alongside English, especially to reach Bahraini and Saudi audiences.'),('Which data law applies in Bahrain?','The Personal Data Protection Law (Law No. 30 of 2018).'),('Do you work with businesses in Bahrain?','Yes, remotely from Muscat, with clear reporting and WhatsApp updates.')]),
 'kuwait': dict(
  name='Kuwait', full='the State of Kuwait', the='Kuwait', ar_name='الكويت', flag='🇰🇼', accent='fe-gold',
  cities='Kuwait City, Hawalli, Salmiya, Farwaniya and Ahmadi', currency='Kuwaiti dinar (KWD)', weekend='Friday–Saturday',
  title='Digital Marketing in Kuwait: SEO, Ads & Social Guide (2027) | Hisan Ali',
  desc='Digital marketing in Kuwait: high spending power, Instagram-led commerce, Arabic content, Kuwait data privacy rules, Hala February and 2027 key dates, with SEO and ads tips.',
  h1='Digital Marketing in Kuwait: <br>Where Instagram Became a Shopfront',
  deck='Kuwait has high spending power and a long tradition of businesses selling directly through Instagram and WhatsApp. Customers expect to see, ask and order in one flow. Here is how to plan SEO, ads and social media for that reality.',
  snapshot=[('Audience','Kuwaitis and a large expatriate population, with high average spending.'),('Commerce','Social commerce is deeply rooted: many brands take orders directly through Instagram and WhatsApp.'),('Language','Arabic is essential for Kuwaiti audiences; English serves parts of the market and B2B.'),('Seasonality','February is a standout month, with national celebrations and Hala February.')],
  platforms=[('Instagram','The main shopfront for many Kuwaiti brands: discovery, proof and ordering.'),('Snapchat','Strong with young Kuwaitis and for local influencers.'),('Google Search & Maps','Essential for services, clinics and local businesses.'),('TikTok','Fast-growing for discovery and product content.'),('WhatsApp','Where orders and enquiries are completed.')],
  language='Write in Arabic with a natural Gulf register for consumer brands, and keep English for B2B and expatriate audiences. Kuwaiti search terms and spellings can differ from other Gulf countries, so check them separately.',
  law=('Kuwait Data Privacy Protection Regulation, supervised by CITRA','Kuwait’s data privacy rules require consent for processing, give individuals rights to access and delete their data, and require breach notification. Treat customer data from social commerce carefully.'),
  search='Many Kuwaiti brands rely only on Instagram. A fast website, Google Business Profile and Google Ads give you a second channel competitors often neglect, and capture customers who search before they buy.',
  dates=[('February','Hala February','A month-long national festival of events and shopping; in 2027 much of it overlaps Ramadan.'),('25 Feb','Kuwait National Day','National celebrations; respectful, patriotic creative.'),('26 Feb','Liberation Day','Marks the liberation of Kuwait in 1991.'),('Summer','Summer travel','Many residents travel; delivery and travel offers.'),('Sep','Back to school','Uniforms, devices and tuition.'),('Late Nov','White Friday and 11.11','Online sales moments.')],
  mawlid=True,
  faq=[('Why is Instagram so important in Kuwait?','Many Kuwaiti businesses sell directly through Instagram and WhatsApp, so customers expect to discover, ask and order there.'),('Should Kuwait businesses invest in SEO and Google Ads?','Yes. Many competitors rely only on Instagram, so a strong website, Google profile and search ads can capture customers others miss.'),('How does Ramadan affect February in Kuwait in 2027?','Ramadan is expected to begin around 8 February 2027, so Hala February and the national days on 25–26 February largely fall within it. Plan evening-focused, respectful campaigns.'),('Do you work with businesses in Kuwait?','Yes, remotely from Muscat, in Arabic and English.')]),
}

SOURCES = [
 ('UAE Personal Data Protection Law, Federal Decree-Law No. 45 of 2021', 'https://u.ae/en/about-the-uae/digital-uae/data/data-protection-laws'),
 ('Saudi PDPL becomes fully enforceable on 14 September 2024 (Clyde & Co)', 'https://www.clydeco.com/en/insights/2024/09/saudi-arabia-s-personal-data-protection-law-become'),
 ('Kuwait Data Privacy Protection Regulations (Al Tamimi & Co)', 'https://www.tamimi.com/news/kuwait-data-privacy-protection-regulations/'),
 ('Riyadh Season 2026 opens on 21 October (Gulf News)', 'https://gulfnews.com/world/gulf/saudi/riyadh-season-2026-to-begin-on-october-21-with-10-weeks-of-entertainment-1.500689955'),
 ('Expected 2027 Islamic dates follow Umm al-Qura projections (timeanddate.com)', 'https://www.timeanddate.com/holidays/'),
]

# Extra depth per country: (sector, why it matters) and (mistake, fix)
EXTRA = {
 'uae': dict(
  sectors=[('Real estate','Off-plan and rental demand from residents and overseas buyers; long research cycles mean retargeting and WhatsApp follow-up matter.'),('Hospitality and F&B','Constant openings and tourists; Google Maps, reviews and Instagram decide where people go tonight.'),('Education and training','Schools, universities and courses with strong seasonal enrolment peaks.'),('Professional services and B2B','Free-zone companies, consultancies and SaaS, where LinkedIn and search lead.')],
  mistakes=[('Copying Dubai strategy to Abu Dhabi','Audiences, competitors and search terms differ; build separate campaigns and pages.'),('English only','Arabic campaigns are cheaper and reach Emirati decision makers competitors ignore.'),('Bidding on broad city terms','“Dubai” plus a service is expensive; specific areas, services and long-tail searches convert better.'),('Ignoring the Saturday–Sunday weekend','Peak days differ from neighbouring countries; schedule ads and posts on UAE time and habits.')]),
 'ksa': dict(
  sectors=[('Entertainment and tourism','New events, attractions and seasons create fresh demand every year.'),('Retail and e-commerce','Large, mobile-first shoppers who discover on Snapchat and TikTok and compare on Google.'),('F&B and cafés','A fast-growing café and restaurant culture driven by video and influencers.'),('B2B and giga-project supply chains','Construction, logistics and professional services serving major national projects.')],
  mistakes=[('Translating Gulf or Egyptian Arabic copy','Saudi audiences notice; write in a natural Saudi register.'),('Treating the Kingdom as one city','Riyadh, Jeddah and the Eastern Province need separate targeting and creative.'),('Skipping Snapchat','For many consumer categories it is a primary channel, not optional.'),('Underestimating compliance','PDPL is enforced; consent, Arabic privacy notices and data transfer rules matter.')]),
 'qatar': dict(
  sectors=[('Hospitality and events','Hotels, restaurants and a busy events calendar.'),('Real estate','Lusail, The Pearl and West Bay attract residents and investors.'),('Education and healthcare','High-value services where trust and reviews decide.'),('B2B and energy-linked services','Professional services, construction and suppliers, often via LinkedIn and search.')],
  mistakes=[('Running big broad campaigns','Small audiences saturate fast; target precisely and refresh creative.'),('Showing the same retargeting ad for weeks','Frequency climbs quickly in a small market; cap it.'),('English-only branding','Polished Arabic builds credibility with Qatari customers.'),('Neglecting reviews','In a small, connected market, reputation compounds both ways.')]),
 'bahrain': dict(
  sectors=[('Financial services and fintech','A regional finance hub where LinkedIn and search matter.'),('F&B and hospitality','Restaurants, cafés and hotels serving residents and weekend visitors.'),('Retail and malls','Shopping destinations popular with Saudi visitors.'),('Events and motorsport','Formula 1 and other events create seasonal peaks.')],
  mistakes=[('Forgetting Saudi visitors','Weekend trade from the Eastern Province can be a second market.'),('Over-segmenting by city','The island is small; national targeting with area pages usually works better.'),('One language only','Arabic and English versions reach different audiences.'),('No Google presence','Visitors search Google Maps before choosing where to eat or shop.')]),
 'kuwait': dict(
  sectors=[('Fashion, beauty and perfume','Instagram-led brands with loyal customers and influencer-driven launches.'),('F&B and home businesses','A strong food scene with many orders through Instagram and WhatsApp.'),('Clinics and wellness','High-value services where Google search and reviews drive bookings.'),('Retail and e-commerce','High spending power and strong seasonal peaks around February and Ramadan.')],
  mistakes=[('Relying only on Instagram','Algorithm changes can cut reach overnight; build Google and a website as a second channel.'),('No order tracking','Orders in DMs are hard to measure; tag WhatsApp clicks and use simple order codes.'),('Ignoring February timing','In 2027 Hala February and the national days overlap Ramadan; adjust tone and timing.'),('Weak Arabic copy','Kuwaiti customers expect natural Gulf Arabic, not stiff translation.')]),
}
